// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package user_db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) error
	CreateEmployee(ctx context.Context, userID uuid.UUID) (GikiWalletEmployeeProfile, error)
	CreateStudent(ctx context.Context, arg CreateStudentParams) (GikiWalletStudentProfile, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	DeleteAllTokensForUser(ctx context.Context, userID uuid.UUID) error
	DeleteUser(ctx context.Context, id uuid.UUID) error
	GetUserAuthByEmail(ctx context.Context, email string) (GetUserAuthByEmailRow, error)
	GetUserAuthByID(ctx context.Context, id uuid.UUID) (GetUserAuthByIDRow, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByRegOrEmail(ctx context.Context, arg GetUserByRegOrEmailParams) (GetUserByRegOrEmailRow, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error)
	UpdateUserDetails(ctx context.Context, arg UpdateUserDetailsParams) (UpdateUserDetailsRow, error)
	UpdateUserPasswordWithAlgo(ctx context.Context, arg UpdateUserPasswordWithAlgoParams) (UpdateUserPasswordWithAlgoRow, error)
	UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (UpdateUserStatusRow, error)
	UpdateUserVerification(ctx context.Context, id uuid.UUID) (UpdateUserVerificationRow, error)
}

var _ Querier = (*Queries)(nil)
