// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package user_db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessToken = `-- name: CreateAccessToken :exec
INSERT INTO giki_wallet.access_tokens(token_hash, user_id, type, expires_at)
VALUES ($1, $2, $3, $4)
`

type CreateAccessTokenParams struct {
	TokenHash string    `json:"token_hash"`
	UserID    uuid.UUID `json:"user_id"`
	Type      string    `json:"type"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) error {
	_, err := q.db.Exec(ctx, createAccessToken,
		arg.TokenHash,
		arg.UserID,
		arg.Type,
		arg.ExpiresAt,
	)
	return err
}

const createEmployee = `-- name: CreateEmployee :one
INSERT INTO giki_wallet.employee_profiles(user_id)
Values ($1)
RETURNING user_id, employee_id, designation, department
`

func (q *Queries) CreateEmployee(ctx context.Context, userID uuid.UUID) (GikiWalletEmployeeProfile, error) {
	row := q.db.QueryRow(ctx, createEmployee, userID)
	var i GikiWalletEmployeeProfile
	err := row.Scan(
		&i.UserID,
		&i.EmployeeID,
		&i.Designation,
		&i.Department,
	)
	return i, err
}

const createStudent = `-- name: CreateStudent :one
INSERT INTO giki_wallet.student_profiles(user_id, reg_id, batch_year)
VALUES ($1, $2, $3)
RETURNING user_id, reg_id, degree_program, batch_year
`

type CreateStudentParams struct {
	UserID    uuid.UUID   `json:"user_id"`
	RegID     string      `json:"reg_id"`
	BatchYear pgtype.Int4 `json:"batch_year"`
}

func (q *Queries) CreateStudent(ctx context.Context, arg CreateStudentParams) (GikiWalletStudentProfile, error) {
	row := q.db.QueryRow(ctx, createStudent, arg.UserID, arg.RegID, arg.BatchYear)
	var i GikiWalletStudentProfile
	err := row.Scan(
		&i.UserID,
		&i.RegID,
		&i.DegreeProgram,
		&i.BatchYear,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO giki_wallet.users(name, email, phone_number, auth_provider, password_hash, password_algo, is_active, is_verified, user_type)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, name, email, phone_number, auth_provider, external_id, is_active, is_verified, user_type, created_at, updated_at
`

type CreateUserParams struct {
	Name         string `json:"name"`
	Email        string `json:"email"`
	PhoneNumber  string `json:"phone_number"`
	AuthProvider string `json:"auth_provider"`
	PasswordHash string `json:"password_hash"`
	PasswordAlgo string `json:"password_algo"`
	IsActive     bool   `json:"is_active"`
	IsVerified   bool   `json:"is_verified"`
	UserType     string `json:"user_type"`
}

type CreateUserRow struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PhoneNumber  string      `json:"phone_number"`
	AuthProvider string      `json:"auth_provider"`
	ExternalID   pgtype.Text `json:"external_id"`
	IsActive     bool        `json:"is_active"`
	IsVerified   bool        `json:"is_verified"`
	UserType     string      `json:"user_type"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.PhoneNumber,
		arg.AuthProvider,
		arg.PasswordHash,
		arg.PasswordAlgo,
		arg.IsActive,
		arg.IsVerified,
		arg.UserType,
	)
	var i CreateUserRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.AuthProvider,
		&i.ExternalID,
		&i.IsActive,
		&i.IsVerified,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAllTokensForUser = `-- name: DeleteAllTokensForUser :exec
DELETE FROM giki_wallet.access_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteAllTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAllTokensForUser, userID)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM giki_wallet.users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUserAuthByEmail = `-- name: GetUserAuthByEmail :one
SELECT id, name, email, phone_number, auth_provider, external_id, password_hash, password_algo, is_active, is_verified, user_type, created_at, updated_at
FROM giki_wallet.users
WHERE giki_wallet.users.email = $1
`

func (q *Queries) GetUserAuthByEmail(ctx context.Context, email string) (GikiWalletUser, error) {
	row := q.db.QueryRow(ctx, getUserAuthByEmail, email)
	var i GikiWalletUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.AuthProvider,
		&i.ExternalID,
		&i.PasswordHash,
		&i.PasswordAlgo,
		&i.IsActive,
		&i.IsVerified,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserAuthByID = `-- name: GetUserAuthByID :one
SELECT id, name, email, phone_number, auth_provider, external_id, password_hash, password_algo, is_active, is_verified, user_type, created_at, updated_at
FROM giki_wallet.users
WHERE id = $1
`

func (q *Queries) GetUserAuthByID(ctx context.Context, id uuid.UUID) (GikiWalletUser, error) {
	row := q.db.QueryRow(ctx, getUserAuthByID, id)
	var i GikiWalletUser
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.AuthProvider,
		&i.ExternalID,
		&i.PasswordHash,
		&i.PasswordAlgo,
		&i.IsActive,
		&i.IsVerified,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, phone_number, auth_provider, external_id, is_active, is_verified, user_type, created_at, updated_at
FROM giki_wallet.users
WHERE giki_wallet.users.email = $1
`

type GetUserByEmailRow struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PhoneNumber  string      `json:"phone_number"`
	AuthProvider string      `json:"auth_provider"`
	ExternalID   pgtype.Text `json:"external_id"`
	IsActive     bool        `json:"is_active"`
	IsVerified   bool        `json:"is_verified"`
	UserType     string      `json:"user_type"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i GetUserByEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.AuthProvider,
		&i.ExternalID,
		&i.IsActive,
		&i.IsVerified,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, name, email, phone_number, auth_provider, external_id, is_active, is_verified, user_type, created_at, updated_at
FROM giki_wallet.users
WHERE id = $1
`

type GetUserByIDRow struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PhoneNumber  string      `json:"phone_number"`
	AuthProvider string      `json:"auth_provider"`
	ExternalID   pgtype.Text `json:"external_id"`
	IsActive     bool        `json:"is_active"`
	IsVerified   bool        `json:"is_verified"`
	UserType     string      `json:"user_type"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.AuthProvider,
		&i.ExternalID,
		&i.IsActive,
		&i.IsVerified,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByRegOrEmail = `-- name: GetUserByRegOrEmail :one
SELECT u.id, u.name, u.email, u.phone_number, u.auth_provider, u.external_id, u.is_active, u.is_verified, u.user_type, u.created_at, u.updated_at
FROM giki_wallet.users as u
JOIN giki_wallet.student_profiles as s ON u.id = s.user_id
WHERE u.email = $1 or s.reg_id = $2
`

type GetUserByRegOrEmailParams struct {
	Email string `json:"email"`
	RegID string `json:"reg_id"`
}

type GetUserByRegOrEmailRow struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PhoneNumber  string      `json:"phone_number"`
	AuthProvider string      `json:"auth_provider"`
	ExternalID   pgtype.Text `json:"external_id"`
	IsActive     bool        `json:"is_active"`
	IsVerified   bool        `json:"is_verified"`
	UserType     string      `json:"user_type"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) GetUserByRegOrEmail(ctx context.Context, arg GetUserByRegOrEmailParams) (GetUserByRegOrEmailRow, error) {
	row := q.db.QueryRow(ctx, getUserByRegOrEmail, arg.Email, arg.RegID)
	var i GetUserByRegOrEmailRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.AuthProvider,
		&i.ExternalID,
		&i.IsActive,
		&i.IsVerified,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, phone_number, is_active, is_verified, user_type, created_at, updated_at, COUNT(*) OVER() as total_count
FROM giki_wallet.users
WHERE 
    ($1::text = '' OR 
     name ILIKE '%' || $1::text || '%' OR 
     email ILIKE '%' || $1::text || '%' OR 
     phone_number ILIKE '%' || $1::text || '%')
    AND ($2::text = '' OR user_type = $2::text)
    AND (
        $3::text = ''
        OR ($3::text = 'active' AND is_active = TRUE)
        OR ($3::text = 'inactive' AND is_active = FALSE)
    )
ORDER BY created_at DESC
LIMIT $5 OFFSET $4
`

type ListUsersParams struct {
	Search       string `json:"search"`
	UserType     string `json:"user_type"`
	FilterStatus string `json:"filter_status"`
	Offset       int32  `json:"offset"`
	Limit        int32  `json:"limit"`
}

type ListUsersRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Email       string    `json:"email"`
	PhoneNumber string    `json:"phone_number"`
	IsActive    bool      `json:"is_active"`
	IsVerified  bool      `json:"is_verified"`
	UserType    string    `json:"user_type"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
	TotalCount  int64     `json:"total_count"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]ListUsersRow, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Search,
		arg.UserType,
		arg.FilterStatus,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUsersRow
	for rows.Next() {
		var i ListUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.PhoneNumber,
			&i.IsActive,
			&i.IsVerified,
			&i.UserType,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUserDetails = `-- name: UpdateUserDetails :one
UPDATE giki_wallet.users
SET 
    name = COALESCE(NULLIF($2::text, ''), name),
    email = COALESCE(NULLIF($3::text, ''), email),
    phone_number = COALESCE(NULLIF($4::text, ''), phone_number),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, phone_number, auth_provider, external_id, is_active, is_verified, user_type, created_at, updated_at
`

type UpdateUserDetailsParams struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Email       string    `json:"email"`
	PhoneNumber string    `json:"phone_number"`
}

type UpdateUserDetailsRow struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PhoneNumber  string      `json:"phone_number"`
	AuthProvider string      `json:"auth_provider"`
	ExternalID   pgtype.Text `json:"external_id"`
	IsActive     bool        `json:"is_active"`
	IsVerified   bool        `json:"is_verified"`
	UserType     string      `json:"user_type"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateUserDetails(ctx context.Context, arg UpdateUserDetailsParams) (UpdateUserDetailsRow, error) {
	row := q.db.QueryRow(ctx, updateUserDetails,
		arg.ID,
		arg.Name,
		arg.Email,
		arg.PhoneNumber,
	)
	var i UpdateUserDetailsRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.AuthProvider,
		&i.ExternalID,
		&i.IsActive,
		&i.IsVerified,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserPasswordWithAlgo = `-- name: UpdateUserPasswordWithAlgo :one
UPDATE giki_wallet.users
SET password_hash = $2, password_algo = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, phone_number, is_active, is_verified, user_type, created_at, updated_at
`

type UpdateUserPasswordWithAlgoParams struct {
	ID           uuid.UUID `json:"id"`
	PasswordHash string    `json:"password_hash"`
	PasswordAlgo string    `json:"password_algo"`
}

type UpdateUserPasswordWithAlgoRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Email       string    `json:"email"`
	PhoneNumber string    `json:"phone_number"`
	IsActive    bool      `json:"is_active"`
	IsVerified  bool      `json:"is_verified"`
	UserType    string    `json:"user_type"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateUserPasswordWithAlgo(ctx context.Context, arg UpdateUserPasswordWithAlgoParams) (UpdateUserPasswordWithAlgoRow, error) {
	row := q.db.QueryRow(ctx, updateUserPasswordWithAlgo, arg.ID, arg.PasswordHash, arg.PasswordAlgo)
	var i UpdateUserPasswordWithAlgoRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.IsActive,
		&i.IsVerified,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserStatus = `-- name: UpdateUserStatus :one
UPDATE giki_wallet.users
SET is_active = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, phone_number, is_active, is_verified, user_type, created_at, updated_at
`

type UpdateUserStatusParams struct {
	ID       uuid.UUID `json:"id"`
	IsActive bool      `json:"is_active"`
}

type UpdateUserStatusRow struct {
	ID          uuid.UUID `json:"id"`
	Name        string    `json:"name"`
	Email       string    `json:"email"`
	PhoneNumber string    `json:"phone_number"`
	IsActive    bool      `json:"is_active"`
	IsVerified  bool      `json:"is_verified"`
	UserType    string    `json:"user_type"`
	CreatedAt   time.Time `json:"created_at"`
	UpdatedAt   time.Time `json:"updated_at"`
}

func (q *Queries) UpdateUserStatus(ctx context.Context, arg UpdateUserStatusParams) (UpdateUserStatusRow, error) {
	row := q.db.QueryRow(ctx, updateUserStatus, arg.ID, arg.IsActive)
	var i UpdateUserStatusRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.IsActive,
		&i.IsVerified,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateUserVerification = `-- name: UpdateUserVerification :one
UPDATE giki_wallet.users
SET is_verified = TRUE, is_active = TRUE, updated_at = NOW()
WHERE id = $1
RETURNING id, name, email, phone_number, auth_provider, external_id, is_active, is_verified, user_type, created_at, updated_at
`

type UpdateUserVerificationRow struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PhoneNumber  string      `json:"phone_number"`
	AuthProvider string      `json:"auth_provider"`
	ExternalID   pgtype.Text `json:"external_id"`
	IsActive     bool        `json:"is_active"`
	IsVerified   bool        `json:"is_verified"`
	UserType     string      `json:"user_type"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateUserVerification(ctx context.Context, id uuid.UUID) (UpdateUserVerificationRow, error) {
	row := q.db.QueryRow(ctx, updateUserVerification, id)
	var i UpdateUserVerificationRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.PhoneNumber,
		&i.AuthProvider,
		&i.ExternalID,
		&i.IsActive,
		&i.IsVerified,
		&i.UserType,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
