// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package auth

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAccessToken = `-- name: CreateAccessToken :one
INSERT INTO giki_wallet.access_tokens(token_hash, user_id, type, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING token_hash, user_id, type, expires_at, created_at
`

type CreateAccessTokenParams struct {
	TokenHash string    `json:"token_hash"`
	UserID    uuid.UUID `json:"user_id"`
	Type      string    `json:"type"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (GikiWalletAccessToken, error) {
	row := q.db.QueryRow(ctx, createAccessToken,
		arg.TokenHash,
		arg.UserID,
		arg.Type,
		arg.ExpiresAt,
	)
	var i GikiWalletAccessToken
	err := row.Scan(
		&i.TokenHash,
		&i.UserID,
		&i.Type,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one

INSERT INTO giki_wallet.refresh_tokens(token_hash, expires_at, user_id)
VALUES ($1, $2, $3)
RETURNING id, token_hash, expires_at, revoked_at, replaced_by_token, device_info, ip_address, user_id, created_at, updated_at
`

type CreateRefreshTokenParams struct {
	TokenHash string           `json:"token_hash"`
	ExpiresAt pgtype.Timestamp `json:"expires_at"`
	UserID    uuid.UUID        `json:"user_id"`
}

func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (GikiWalletRefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken, arg.TokenHash, arg.ExpiresAt, arg.UserID)
	var i GikiWalletRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByToken,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteAccessToken = `-- name: DeleteAccessToken :exec
DELETE FROM giki_wallet.access_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteAccessToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteAccessToken, tokenHash)
	return err
}

const getRefreshTokenByHash = `-- name: GetRefreshTokenByHash :one
SELECT id, token_hash, expires_at, revoked_at, replaced_by_token, device_info, ip_address, user_id, created_at, updated_at FROM giki_wallet.refresh_tokens
WHERE token_hash = $1 LIMIT 1
`

func (q *Queries) GetRefreshTokenByHash(ctx context.Context, tokenHash string) (GikiWalletRefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshTokenByHash, tokenHash)
	var i GikiWalletRefreshToken
	err := row.Scan(
		&i.ID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.ReplacedByToken,
		&i.DeviceInfo,
		&i.IpAddress,
		&i.UserID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByTokenHash = `-- name: GetUserByTokenHash :one

SELECT user_id, type, expires_at
FROM giki_wallet.access_tokens
WHERE token_hash = $1
`

type GetUserByTokenHashRow struct {
	UserID    uuid.UUID `json:"user_id"`
	Type      string    `json:"type"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) GetUserByTokenHash(ctx context.Context, tokenHash string) (GetUserByTokenHashRow, error) {
	row := q.db.QueryRow(ctx, getUserByTokenHash, tokenHash)
	var i GetUserByTokenHashRow
	err := row.Scan(&i.UserID, &i.Type, &i.ExpiresAt)
	return i, err
}

const replaceRefreshToken = `-- name: ReplaceRefreshToken :exec
UPDATE giki_wallet.refresh_tokens
SET revoked_at = NOW(), replaced_by_token = $2, updated_at = NOW()
WHERE token_hash = $1
`

type ReplaceRefreshTokenParams struct {
	TokenHash       string      `json:"token_hash"`
	ReplacedByToken pgtype.Text `json:"replaced_by_token"`
}

func (q *Queries) ReplaceRefreshToken(ctx context.Context, arg ReplaceRefreshTokenParams) error {
	_, err := q.db.Exec(ctx, replaceRefreshToken, arg.TokenHash, arg.ReplacedByToken)
	return err
}

const revokeAllRefreshTokensForUser = `-- name: RevokeAllRefreshTokensForUser :exec
UPDATE giki_wallet.refresh_tokens
SET revoked_at = NOW(), updated_at = NOW()
WHERE user_id = $1 AND revoked_at IS NULL
`

func (q *Queries) RevokeAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeAllRefreshTokensForUser, userID)
	return err
}
