// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package auth

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAccessToken(ctx context.Context, arg CreateAccessTokenParams) (GikiWalletAccessToken, error)
	CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (GikiWalletRefreshToken, error)
	DeleteAccessToken(ctx context.Context, tokenHash string) error
	GetRefreshTokenByHash(ctx context.Context, tokenHash string) (GikiWalletRefreshToken, error)
	GetUserByTokenHash(ctx context.Context, tokenHash string) (GetUserByTokenHashRow, error)
	ReplaceRefreshToken(ctx context.Context, arg ReplaceRefreshTokenParams) error
	RevokeAllRefreshTokensForUser(ctx context.Context, userID uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
