// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package audit_db

import (
	"context"
)

type Querier interface {
	CountSystemAuditLogs(ctx context.Context) (int64, error)
	CreateSystemAuditLog(ctx context.Context, arg CreateSystemAuditLogParams) error
	ListSystemAuditLogs(ctx context.Context, arg ListSystemAuditLogsParams) ([]ListSystemAuditLogsRow, error)
}

var _ Querier = (*Queries)(nil)
