// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package audit_db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countSystemAuditLogs = `-- name: CountSystemAuditLogs :one
SELECT COUNT(*) FROM giki_wallet.system_audit_logs
`

func (q *Queries) CountSystemAuditLogs(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countSystemAuditLogs)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSystemAuditLog = `-- name: CreateSystemAuditLog :exec
INSERT INTO giki_wallet.system_audit_logs (actor_id, action, target_id, details, ip_address, user_agent, status, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type CreateSystemAuditLogParams struct {
	ActorID   pgtype.UUID      `json:"actor_id"`
	Action    string           `json:"action"`
	TargetID  pgtype.UUID      `json:"target_id"`
	Details   []byte           `json:"details"`
	IpAddress string           `json:"ip_address"`
	UserAgent pgtype.Text      `json:"user_agent"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) CreateSystemAuditLog(ctx context.Context, arg CreateSystemAuditLogParams) error {
	_, err := q.db.Exec(ctx, createSystemAuditLog,
		arg.ActorID,
		arg.Action,
		arg.TargetID,
		arg.Details,
		arg.IpAddress,
		arg.UserAgent,
		arg.Status,
		arg.CreatedAt,
	)
	return err
}

const listSystemAuditLogs = `-- name: ListSystemAuditLogs :many
SELECT 
    l.id, l.action, l.ip_address, l.user_agent, l.status, l.created_at, l.details,
    l.actor_id, u.name as actor_name, u.email as actor_email,
    l.target_id, t.name as target_name, t.email as target_email
FROM giki_wallet.system_audit_logs l
LEFT JOIN giki_wallet.users u ON l.actor_id = u.id
LEFT JOIN giki_wallet.users t ON l.target_id = t.id
ORDER BY l.created_at DESC
LIMIT $1 OFFSET $2
`

type ListSystemAuditLogsParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type ListSystemAuditLogsRow struct {
	ID          uuid.UUID        `json:"id"`
	Action      string           `json:"action"`
	IpAddress   string           `json:"ip_address"`
	UserAgent   pgtype.Text      `json:"user_agent"`
	Status      string           `json:"status"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
	Details     []byte           `json:"details"`
	ActorID     pgtype.UUID      `json:"actor_id"`
	ActorName   pgtype.Text      `json:"actor_name"`
	ActorEmail  pgtype.Text      `json:"actor_email"`
	TargetID    pgtype.UUID      `json:"target_id"`
	TargetName  pgtype.Text      `json:"target_name"`
	TargetEmail pgtype.Text      `json:"target_email"`
}

func (q *Queries) ListSystemAuditLogs(ctx context.Context, arg ListSystemAuditLogsParams) ([]ListSystemAuditLogsRow, error) {
	rows, err := q.db.Query(ctx, listSystemAuditLogs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSystemAuditLogsRow
	for rows.Next() {
		var i ListSystemAuditLogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Action,
			&i.IpAddress,
			&i.UserAgent,
			&i.Status,
			&i.CreatedAt,
			&i.Details,
			&i.ActorID,
			&i.ActorName,
			&i.ActorEmail,
			&i.TargetID,
			&i.TargetName,
			&i.TargetEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
