// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package feedback_db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type CurrentStatus string

const (
	CurrentStatusPENDING CurrentStatus = "PENDING"
	CurrentStatusSUCCESS CurrentStatus = "SUCCESS"
	CurrentStatusFAILED  CurrentStatus = "FAILED"
	CurrentStatusUNKNOWN CurrentStatus = "UNKNOWN"
)

func (e *CurrentStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CurrentStatus(s)
	case string:
		*e = CurrentStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for CurrentStatus: %T", src)
	}
	return nil
}

type NullCurrentStatus struct {
	CurrentStatus CurrentStatus `json:"current_status"`
	Valid         bool          `json:"valid"` // Valid is true if CurrentStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCurrentStatus) Scan(value interface{}) error {
	if value == nil {
		ns.CurrentStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CurrentStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCurrentStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CurrentStatus), nil
}

type GikiWalletAuditEventType string

const (
	GikiWalletAuditEventTypeTOPUPREQUEST    GikiWalletAuditEventType = "TOPUP_REQUEST"
	GikiWalletAuditEventTypeCARDCALLBACK    GikiWalletAuditEventType = "CARD_CALLBACK"
	GikiWalletAuditEventTypeMWALLETCALLBACK GikiWalletAuditEventType = "MWALLET_CALLBACK"
	GikiWalletAuditEventTypeINQUIRYRESULT   GikiWalletAuditEventType = "INQUIRY_RESULT"
)

func (e *GikiWalletAuditEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = GikiWalletAuditEventType(s)
	case string:
		*e = GikiWalletAuditEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for GikiWalletAuditEventType: %T", src)
	}
	return nil
}

type NullGikiWalletAuditEventType struct {
	GikiWalletAuditEventType GikiWalletAuditEventType `json:"giki_wallet_audit_event_type"`
	Valid                    bool                     `json:"valid"` // Valid is true if GikiWalletAuditEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullGikiWalletAuditEventType) Scan(value interface{}) error {
	if value == nil {
		ns.GikiWalletAuditEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.GikiWalletAuditEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullGikiWalletAuditEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.GikiWalletAuditEventType), nil
}

type GikiTransportDriver struct {
	ID            uuid.UUID   `json:"id"`
	Name          string      `json:"name"`
	PhoneNumber   string      `json:"phone_number"`
	LicenseNumber pgtype.Text `json:"license_number"`
	IsActive      pgtype.Bool `json:"is_active"`
	CreatedAt     time.Time   `json:"created_at"`
	UpdatedAt     time.Time   `json:"updated_at"`
}

type GikiTransportQuotaRule struct {
	UserRole              string `json:"user_role"`
	Direction             string `json:"direction"`
	WeeklyLimit           int32  `json:"weekly_limit"`
	AllowDependentBooking bool   `json:"allow_dependent_booking"`
}

type GikiTransportRoute struct {
	ID                               uuid.UUID   `json:"id"`
	Name                             string      `json:"name"`
	OriginStopID                     uuid.UUID   `json:"origin_stop_id"`
	DestinationStopID                uuid.UUID   `json:"destination_stop_id"`
	IsActive                         pgtype.Bool `json:"is_active"`
	DefaultBookingOpenOffsetMinutes  pgtype.Int4 `json:"default_booking_open_offset_minutes"`
	DefaultBookingCloseOffsetMinutes pgtype.Int4 `json:"default_booking_close_offset_minutes"`
	CreatedAt                        time.Time   `json:"created_at"`
}

type GikiTransportRouteMasterStop struct {
	ID                   uuid.UUID `json:"id"`
	RouteID              uuid.UUID `json:"route_id"`
	StopID               uuid.UUID `json:"stop_id"`
	DefaultSequenceOrder int32     `json:"default_sequence_order"`
	IsDefaultActive      bool      `json:"is_default_active"`
	CreatedAt            time.Time `json:"created_at"`
}

type GikiTransportRouteWeeklySchedule struct {
	ID            uuid.UUID          `json:"id"`
	RouteID       uuid.UUID          `json:"route_id"`
	DayOfWeek     int32              `json:"day_of_week"`
	DepartureTime pgtype.Time        `json:"departure_time"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type GikiTransportStop struct {
	ID        uuid.UUID `json:"id"`
	Address   string    `json:"address"`
	CreatedAt time.Time `json:"created_at"`
}

type GikiTransportTicket struct {
	ID                uuid.UUID `json:"id"`
	TripID            uuid.UUID `json:"trip_id"`
	UserID            uuid.UUID `json:"user_id"`
	SerialNo          int32     `json:"serial_no"`
	TicketCode        string    `json:"ticket_code"`
	PickupStopID      uuid.UUID `json:"pickup_stop_id"`
	DropoffStopID     uuid.UUID `json:"dropoff_stop_id"`
	PassengerName     string    `json:"passenger_name"`
	PassengerRelation string    `json:"passenger_relation"`
	Status            string    `json:"status"`
	BookingTime       time.Time `json:"booking_time"`
	UpdatedAt         time.Time `json:"updated_at"`
	PricePaid         int32     `json:"price_paid"`
}

type GikiTransportTrip struct {
	ID                        uuid.UUID   `json:"id"`
	RouteID                   uuid.UUID   `json:"route_id"`
	DriverID                  pgtype.UUID `json:"driver_id"`
	DepartureTime             time.Time   `json:"departure_time"`
	BookingOpenOffsetMinutes  int32       `json:"booking_open_offset_minutes"`
	BookingCloseOffsetMinutes int32       `json:"booking_close_offset_minutes"`
	Direction                 string      `json:"direction"`
	BasePrice                 int32       `json:"base_price"`
	BusType                   string      `json:"bus_type"`
	TotalCapacity             int32       `json:"total_capacity"`
	AvailableSeats            int32       `json:"available_seats"`
	Status                    pgtype.Text `json:"status"`
	CreatedAt                 time.Time   `json:"created_at"`
	UpdatedAt                 time.Time   `json:"updated_at"`
	ManualStatus              pgtype.Text `json:"manual_status"`
}

type GikiTransportTripHold struct {
	ID                uuid.UUID          `json:"id"`
	TripID            uuid.UUID          `json:"trip_id"`
	UserID            uuid.UUID          `json:"user_id"`
	PickupStopID      uuid.UUID          `json:"pickup_stop_id"`
	DropoffStopID     uuid.UUID          `json:"dropoff_stop_id"`
	PassengerName     pgtype.Text        `json:"passenger_name"`
	PassengerRelation pgtype.Text        `json:"passenger_relation"`
	ExpiresAt         time.Time          `json:"expires_at"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
}

type GikiTransportTripStop struct {
	ID            uuid.UUID `json:"id"`
	TripID        uuid.UUID `json:"trip_id"`
	StopID        uuid.UUID `json:"stop_id"`
	SequenceOrder int32     `json:"sequence_order"`
	CreatedAt     time.Time `json:"created_at"`
}

type GikiWalletAccessToken struct {
	TokenHash string    `json:"token_hash"`
	UserID    uuid.UUID `json:"user_id"`
	Type      string    `json:"type"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type GikiWalletEmployeeProfile struct {
	UserID      uuid.UUID   `json:"user_id"`
	EmployeeID  string      `json:"employee_id"`
	Designation pgtype.Text `json:"designation"`
	Department  pgtype.Text `json:"department"`
}

type GikiWalletFeedback struct {
	ID        int32       `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
	Rating    int32       `json:"rating"`
	Comment   pgtype.Text `json:"comment"`
	CreatedAt time.Time   `json:"created_at"`
}

type GikiWalletGatewayTransaction struct {
	ID                uuid.UUID     `json:"id"`
	UserID            uuid.UUID     `json:"user_id"`
	IdempotencyKey    uuid.UUID     `json:"idempotency_key"`
	BillRefID         string        `json:"bill_ref_id"`
	TxnRefNo          string        `json:"txn_ref_no"`
	PaymentMethod     string        `json:"payment_method"`
	GatewayRrn        pgtype.Text   `json:"gateway_rrn"`
	Status            CurrentStatus `json:"status"`
	Amount            int64         `json:"amount"`
	RawResponse       []byte        `json:"raw_response"`
	IsPolling         pgtype.Bool   `json:"is_polling"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
	GatewayMessage    pgtype.Text   `json:"gateway_message"`
	GatewayStatusCode pgtype.Text   `json:"gateway_status_code"`
}

type GikiWalletJob struct {
	ID         uuid.UUID   `json:"id"`
	JobType    string      `json:"job_type"`
	Payload    []byte      `json:"payload"`
	Status     string      `json:"status"`
	RunAt      time.Time   `json:"run_at"`
	RetryCount int32       `json:"retry_count"`
	MaxRetries int32       `json:"max_retries"`
	LastError  pgtype.Text `json:"last_error"`
	CreatedAt  time.Time   `json:"created_at"`
	UpdatedAt  time.Time   `json:"updated_at"`
}

type GikiWalletLedger struct {
	ID            uuid.UUID `json:"id"`
	WalletID      uuid.UUID `json:"wallet_id"`
	Amount        int64     `json:"amount"`
	BalanceAfter  int64     `json:"balance_after"`
	TransactionID uuid.UUID `json:"transaction_id"`
	RowHash       string    `json:"row_hash"`
	CreatedAt     time.Time `json:"created_at"`
}

type GikiWalletPaymentAuditLog struct {
	ID           uuid.UUID                `json:"id"`
	EventType    GikiWalletAuditEventType `json:"event_type"`
	RawPayload   []byte                   `json:"raw_payload"`
	TxnRefNo     pgtype.Text              `json:"txn_ref_no"`
	GatewayRef   pgtype.Text              `json:"gateway_ref"`
	UserID       pgtype.UUID              `json:"user_id"`
	Processed    pgtype.Bool              `json:"processed"`
	ProcessedAt  pgtype.Timestamptz       `json:"processed_at"`
	ProcessError pgtype.Text              `json:"process_error"`
	RetryCount   pgtype.Int4              `json:"retry_count"`
	ReceivedAt   time.Time                `json:"received_at"`
}

type GikiWalletRefreshToken struct {
	ID              uuid.UUID        `json:"id"`
	TokenHash       string           `json:"token_hash"`
	ExpiresAt       pgtype.Timestamp `json:"expires_at"`
	RevokedAt       pgtype.Timestamp `json:"revoked_at"`
	ReplacedByToken pgtype.Text      `json:"replaced_by_token"`
	DeviceInfo      pgtype.Text      `json:"device_info"`
	IpAddress       pgtype.Text      `json:"ip_address"`
	UserID          uuid.UUID        `json:"user_id"`
	CreatedAt       time.Time        `json:"created_at"`
	UpdatedAt       time.Time        `json:"updated_at"`
}

type GikiWalletStudentProfile struct {
	UserID        uuid.UUID   `json:"user_id"`
	RegID         string      `json:"reg_id"`
	DegreeProgram pgtype.Text `json:"degree_program"`
	BatchYear     pgtype.Int4 `json:"batch_year"`
}

type GikiWalletSystemAuditLog struct {
	ID        uuid.UUID        `json:"id"`
	ActorID   pgtype.UUID      `json:"actor_id"`
	Action    string           `json:"action"`
	TargetID  pgtype.UUID      `json:"target_id"`
	Details   []byte           `json:"details"`
	IpAddress string           `json:"ip_address"`
	UserAgent pgtype.Text      `json:"user_agent"`
	Status    string           `json:"status"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}

type GikiWalletSystemConfig struct {
	Key         string             `json:"key"`
	Value       string             `json:"value"`
	Description pgtype.Text        `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type GikiWalletTransaction struct {
	ID          uuid.UUID   `json:"id"`
	Type        string      `json:"type"`
	ReferenceID string      `json:"reference_id"`
	Description pgtype.Text `json:"description"`
	CreatedAt   time.Time   `json:"created_at"`
}

type GikiWalletUser struct {
	ID           uuid.UUID   `json:"id"`
	Name         string      `json:"name"`
	Email        string      `json:"email"`
	PhoneNumber  string      `json:"phone_number"`
	AuthProvider string      `json:"auth_provider"`
	ExternalID   pgtype.Text `json:"external_id"`
	PasswordHash string      `json:"password_hash"`
	PasswordAlgo string      `json:"password_algo"`
	IsActive     bool        `json:"is_active"`
	IsVerified   bool        `json:"is_verified"`
	UserType     string      `json:"user_type"`
	CreatedAt    time.Time   `json:"created_at"`
	UpdatedAt    time.Time   `json:"updated_at"`
	Gender       pgtype.Text `json:"gender"`
}

type GikiWalletWallet struct {
	ID        uuid.UUID   `json:"id"`
	UserID    pgtype.UUID `json:"user_id"`
	Name      pgtype.Text `json:"name"`
	Type      pgtype.Text `json:"type"`
	Status    string      `json:"status"`
	Currency  string      `json:"currency"`
	CreatedAt time.Time   `json:"created_at"`
}
