// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package feedback_db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFeedback = `-- name: CreateFeedback :one
INSERT INTO giki_wallet.feedback (
  user_id, rating, comment
) VALUES (
  $1, $2, $3
)
RETURNING id, user_id, rating, comment, created_at
`

type CreateFeedbackParams struct {
	UserID  uuid.UUID   `json:"user_id"`
	Rating  int32       `json:"rating"`
	Comment pgtype.Text `json:"comment"`
}

func (q *Queries) CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (GikiWalletFeedback, error) {
	row := q.db.QueryRow(ctx, createFeedback, arg.UserID, arg.Rating, arg.Comment)
	var i GikiWalletFeedback
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Rating,
		&i.Comment,
		&i.CreatedAt,
	)
	return i, err
}
