// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package feedback_db

import (
	"context"
)

type Querier interface {
	CreateFeedback(ctx context.Context, arg CreateFeedbackParams) (GikiWalletFeedback, error)
}

var _ Querier = (*Queries)(nil)
