// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package wallet_db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (GikiWalletLedger, error)
	CreateTransactionHeader(ctx context.Context, arg CreateTransactionHeaderParams) (CreateTransactionHeaderRow, error)
	CreateWallet(ctx context.Context, arg CreateWalletParams) (GikiWalletWallet, error)
	GetAdminRevenueTransactions(ctx context.Context, arg GetAdminRevenueTransactionsParams) ([]GetAdminRevenueTransactionsRow, error)
	GetLastLedgerHash(ctx context.Context, walletID uuid.UUID) (string, error)
	GetLedgerEntriesByReference(ctx context.Context, referenceID string) ([]GetLedgerEntriesByReferenceRow, error)
	GetLedgerEntriesByWallet(ctx context.Context, arg GetLedgerEntriesByWalletParams) ([]GetLedgerEntriesByWalletRow, error)
	GetOrCreateSystemWalletAtomic(ctx context.Context, arg GetOrCreateSystemWalletAtomicParams) (GikiWalletWallet, error)
	GetOrCreateWalletAtomic(ctx context.Context, arg GetOrCreateWalletAtomicParams) (GikiWalletWallet, error)
	GetSystemWalletByName(ctx context.Context, arg GetSystemWalletByNameParams) (GikiWalletWallet, error)
	GetTransactionHeaderByTypeAndRef(ctx context.Context, arg GetTransactionHeaderByTypeAndRefParams) (GikiWalletTransaction, error)
	GetWallet(ctx context.Context, userID pgtype.UUID) (GikiWalletWallet, error)
	GetWalletBalanceSnapshot(ctx context.Context, walletID uuid.UUID) (int64, error)
	GetWalletForUpdate(ctx context.Context, id uuid.UUID) (GikiWalletWallet, error)
	GetWeeklyWalletStats(ctx context.Context, arg GetWeeklyWalletStatsParams) (GetWeeklyWalletStatsRow, error)
}

var _ Querier = (*Queries)(nil)
