// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package wallet_db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one

INSERT INTO giki_wallet.ledger (wallet_id, amount, transaction_id, balance_after, row_hash)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, wallet_id, amount, balance_after, transaction_id, row_hash, created_at
`

type CreateLedgerEntryParams struct {
	WalletID      uuid.UUID `json:"wallet_id"`
	Amount        int64     `json:"amount"`
	TransactionID uuid.UUID `json:"transaction_id"`
	BalanceAfter  int64     `json:"balance_after"`
	RowHash       string    `json:"row_hash"`
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (GikiWalletLedger, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry,
		arg.WalletID,
		arg.Amount,
		arg.TransactionID,
		arg.BalanceAfter,
		arg.RowHash,
	)
	var i GikiWalletLedger
	err := row.Scan(
		&i.ID,
		&i.WalletID,
		&i.Amount,
		&i.BalanceAfter,
		&i.TransactionID,
		&i.RowHash,
		&i.CreatedAt,
	)
	return i, err
}

const createTransactionHeader = `-- name: CreateTransactionHeader :one
INSERT INTO giki_wallet.transactions(type, reference_id, description)
VALUES ($1, $2, $3)
RETURNING id, created_at
`

type CreateTransactionHeaderParams struct {
	Type        string      `json:"type"`
	ReferenceID string      `json:"reference_id"`
	Description pgtype.Text `json:"description"`
}

type CreateTransactionHeaderRow struct {
	ID        uuid.UUID `json:"id"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateTransactionHeader(ctx context.Context, arg CreateTransactionHeaderParams) (CreateTransactionHeaderRow, error) {
	row := q.db.QueryRow(ctx, createTransactionHeader, arg.Type, arg.ReferenceID, arg.Description)
	var i CreateTransactionHeaderRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}

const createWallet = `-- name: CreateWallet :one
INSERT INTO giki_wallet.wallets (user_id, name, type, status)
VALUES ($1, COALESCE(NULLIF($2, ''), 'Personal Wallet'), $3, $4)
RETURNING id, user_id, name, type, status, currency, created_at
`

type CreateWalletParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Type    pgtype.Text `json:"type"`
	Status  string      `json:"status"`
}

func (q *Queries) CreateWallet(ctx context.Context, arg CreateWalletParams) (GikiWalletWallet, error) {
	row := q.db.QueryRow(ctx, createWallet,
		arg.UserID,
		arg.Column2,
		arg.Type,
		arg.Status,
	)
	var i GikiWalletWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getAdminRevenueTransactions = `-- name: GetAdminRevenueTransactions :many
SELECT
    l.id,
    l.amount,
    l.created_at,
    l.balance_after,
    t.type,
    t.description,
    t.reference_id,

    u.name as user_name,
    u.email as user_email,
    COUNT(*) OVER() as total_count
FROM giki_wallet.ledger l
JOIN giki_wallet.transactions t ON l.transaction_id = t.id
LEFT JOIN giki_wallet.ledger other_side ON t.id = other_side.transaction_id AND other_side.id != l.id
LEFT JOIN giki_wallet.wallets w ON other_side.wallet_id = w.id
LEFT JOIN giki_wallet.users u ON w.user_id = u.id
WHERE l.wallet_id = $1
  AND l.created_at >= $4
  AND l.created_at <= $5
  AND (
      $6::text = '' OR
      u.name ILIKE '%' || $6::text || '%' OR
      u.email ILIKE '%' || $6::text || '%' OR
      t.reference_id ILIKE '%' || $6::text || '%'
  )
ORDER BY l.created_at DESC
LIMIT $2 OFFSET $3
`

type GetAdminRevenueTransactionsParams struct {
	WalletID  uuid.UUID `json:"wallet_id"`
	Limit     int32     `json:"limit"`
	Offset    int32     `json:"offset"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	Search    string    `json:"search"`
}

type GetAdminRevenueTransactionsRow struct {
	ID           uuid.UUID   `json:"id"`
	Amount       int64       `json:"amount"`
	CreatedAt    time.Time   `json:"created_at"`
	BalanceAfter int64       `json:"balance_after"`
	Type         string      `json:"type"`
	Description  pgtype.Text `json:"description"`
	ReferenceID  string      `json:"reference_id"`
	UserName     pgtype.Text `json:"user_name"`
	UserEmail    pgtype.Text `json:"user_email"`
	TotalCount   int64       `json:"total_count"`
}

func (q *Queries) GetAdminRevenueTransactions(ctx context.Context, arg GetAdminRevenueTransactionsParams) ([]GetAdminRevenueTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getAdminRevenueTransactions,
		arg.WalletID,
		arg.Limit,
		arg.Offset,
		arg.StartDate,
		arg.EndDate,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAdminRevenueTransactionsRow
	for rows.Next() {
		var i GetAdminRevenueTransactionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.CreatedAt,
			&i.BalanceAfter,
			&i.Type,
			&i.Description,
			&i.ReferenceID,
			&i.UserName,
			&i.UserEmail,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLastLedgerHash = `-- name: GetLastLedgerHash :one
SELECT row_hash
FROM giki_wallet.ledger
WHERE wallet_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetLastLedgerHash(ctx context.Context, walletID uuid.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getLastLedgerHash, walletID)
	var row_hash string
	err := row.Scan(&row_hash)
	return row_hash, err
}

const getLedgerEntriesByReference = `-- name: GetLedgerEntriesByReference :many
SELECT
    l.id, l.amount, l.balance_after, l.created_at,
    t.type, t.reference_id, t.description
FROM giki_wallet.ledger l
         JOIN giki_wallet.transactions t ON l.transaction_id = t.id
WHERE t.reference_id = $1
`

type GetLedgerEntriesByReferenceRow struct {
	ID           uuid.UUID   `json:"id"`
	Amount       int64       `json:"amount"`
	BalanceAfter int64       `json:"balance_after"`
	CreatedAt    time.Time   `json:"created_at"`
	Type         string      `json:"type"`
	ReferenceID  string      `json:"reference_id"`
	Description  pgtype.Text `json:"description"`
}

func (q *Queries) GetLedgerEntriesByReference(ctx context.Context, referenceID string) ([]GetLedgerEntriesByReferenceRow, error) {
	rows, err := q.db.Query(ctx, getLedgerEntriesByReference, referenceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLedgerEntriesByReferenceRow
	for rows.Next() {
		var i GetLedgerEntriesByReferenceRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.BalanceAfter,
			&i.CreatedAt,
			&i.Type,
			&i.ReferenceID,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLedgerEntriesByWallet = `-- name: GetLedgerEntriesByWallet :many
SELECT
    l.id, l.amount, l.balance_after, l.created_at, COUNT(*) OVER() as total_count,
    t.type, t.reference_id, t.description
FROM giki_wallet.ledger l
         JOIN giki_wallet.transactions t ON l.transaction_id = t.id
WHERE l.wallet_id = $1
ORDER BY l.created_at DESC, l.id DESC
LIMIT $2 OFFSET $3
`

type GetLedgerEntriesByWalletParams struct {
	WalletID uuid.UUID `json:"wallet_id"`
	Limit    int32     `json:"limit"`
	Offset   int32     `json:"offset"`
}

type GetLedgerEntriesByWalletRow struct {
	ID           uuid.UUID   `json:"id"`
	Amount       int64       `json:"amount"`
	BalanceAfter int64       `json:"balance_after"`
	CreatedAt    time.Time   `json:"created_at"`
	TotalCount   int64       `json:"total_count"`
	Type         string      `json:"type"`
	ReferenceID  string      `json:"reference_id"`
	Description  pgtype.Text `json:"description"`
}

func (q *Queries) GetLedgerEntriesByWallet(ctx context.Context, arg GetLedgerEntriesByWalletParams) ([]GetLedgerEntriesByWalletRow, error) {
	rows, err := q.db.Query(ctx, getLedgerEntriesByWallet, arg.WalletID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLedgerEntriesByWalletRow
	for rows.Next() {
		var i GetLedgerEntriesByWalletRow
		if err := rows.Scan(
			&i.ID,
			&i.Amount,
			&i.BalanceAfter,
			&i.CreatedAt,
			&i.TotalCount,
			&i.Type,
			&i.ReferenceID,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrCreateSystemWalletAtomic = `-- name: GetOrCreateSystemWalletAtomic :one
INSERT INTO giki_wallet.wallets (user_id, name, type, status)
VALUES ($1, $2, $3, $4)
ON CONFLICT (name, type) 
WHERE type IN ('SYS_REVENUE', 'SYS_LIABILITY')
DO UPDATE SET status = wallets.status
RETURNING id, user_id, name, type, status, currency, created_at
`

type GetOrCreateSystemWalletAtomicParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Name   pgtype.Text `json:"name"`
	Type   pgtype.Text `json:"type"`
	Status string      `json:"status"`
}

func (q *Queries) GetOrCreateSystemWalletAtomic(ctx context.Context, arg GetOrCreateSystemWalletAtomicParams) (GikiWalletWallet, error) {
	row := q.db.QueryRow(ctx, getOrCreateSystemWalletAtomic,
		arg.UserID,
		arg.Name,
		arg.Type,
		arg.Status,
	)
	var i GikiWalletWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getOrCreateWalletAtomic = `-- name: GetOrCreateWalletAtomic :one
INSERT INTO giki_wallet.wallets (user_id, name, type, status)
VALUES ($1, COALESCE(NULLIF($2, ''), 'Personal Wallet'), $3, $4)
ON CONFLICT (user_id) WHERE type = 'PERSONAL'
DO UPDATE SET status = wallets.status
RETURNING id, user_id, name, type, status, currency, created_at
`

type GetOrCreateWalletAtomicParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Column2 interface{} `json:"column_2"`
	Type    pgtype.Text `json:"type"`
	Status  string      `json:"status"`
}

func (q *Queries) GetOrCreateWalletAtomic(ctx context.Context, arg GetOrCreateWalletAtomicParams) (GikiWalletWallet, error) {
	row := q.db.QueryRow(ctx, getOrCreateWalletAtomic,
		arg.UserID,
		arg.Column2,
		arg.Type,
		arg.Status,
	)
	var i GikiWalletWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getSystemWalletByName = `-- name: GetSystemWalletByName :one
SELECT id, user_id, name, type, status, currency, created_at FROM giki_wallet.wallets
WHERE name = $1
  AND type = $2
LIMIT 1
`

type GetSystemWalletByNameParams struct {
	Name pgtype.Text `json:"name"`
	Type pgtype.Text `json:"type"`
}

func (q *Queries) GetSystemWalletByName(ctx context.Context, arg GetSystemWalletByNameParams) (GikiWalletWallet, error) {
	row := q.db.QueryRow(ctx, getSystemWalletByName, arg.Name, arg.Type)
	var i GikiWalletWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getTransactionHeaderByTypeAndRef = `-- name: GetTransactionHeaderByTypeAndRef :one
SELECT id, type, reference_id, description, created_at FROM giki_wallet.transactions
WHERE type = $1 AND reference_id = $2
`

type GetTransactionHeaderByTypeAndRefParams struct {
	Type        string `json:"type"`
	ReferenceID string `json:"reference_id"`
}

func (q *Queries) GetTransactionHeaderByTypeAndRef(ctx context.Context, arg GetTransactionHeaderByTypeAndRefParams) (GikiWalletTransaction, error) {
	row := q.db.QueryRow(ctx, getTransactionHeaderByTypeAndRef, arg.Type, arg.ReferenceID)
	var i GikiWalletTransaction
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.ReferenceID,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const getWallet = `-- name: GetWallet :one
SELECT id, user_id, name, type, status, currency, created_at FROM giki_wallet.wallets
WHERE user_id = $1
`

func (q *Queries) GetWallet(ctx context.Context, userID pgtype.UUID) (GikiWalletWallet, error) {
	row := q.db.QueryRow(ctx, getWallet, userID)
	var i GikiWalletWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getWalletBalanceSnapshot = `-- name: GetWalletBalanceSnapshot :one
SELECT balance_after
FROM giki_wallet.ledger
WHERE wallet_id = $1
ORDER BY created_at DESC, id DESC
LIMIT 1
`

func (q *Queries) GetWalletBalanceSnapshot(ctx context.Context, walletID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getWalletBalanceSnapshot, walletID)
	var balance_after int64
	err := row.Scan(&balance_after)
	return balance_after, err
}

const getWalletForUpdate = `-- name: GetWalletForUpdate :one

SELECT id, user_id, name, type, status, currency, created_at FROM giki_wallet.wallets
WHERE id = $1
    FOR NO KEY UPDATE
`

func (q *Queries) GetWalletForUpdate(ctx context.Context, id uuid.UUID) (GikiWalletWallet, error) {
	row := q.db.QueryRow(ctx, getWalletForUpdate, id)
	var i GikiWalletWallet
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Type,
		&i.Status,
		&i.Currency,
		&i.CreatedAt,
	)
	return i, err
}

const getWeeklyWalletStats = `-- name: GetWeeklyWalletStats :one
SELECT
    COALESCE(SUM(CASE WHEN amount > 0 THEN amount ELSE 0 END), 0)::BIGINT as total_income,
    COALESCE(SUM(CASE WHEN amount < 0 THEN amount ELSE 0 END), 0)::BIGINT as total_refunds,
    COUNT(*) as transaction_count
FROM giki_wallet.ledger
WHERE wallet_id = $1
  AND created_at >= $2
  AND created_at <= $3
`

type GetWeeklyWalletStatsParams struct {
	WalletID  uuid.UUID `json:"wallet_id"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

type GetWeeklyWalletStatsRow struct {
	TotalIncome      int64 `json:"total_income"`
	TotalRefunds     int64 `json:"total_refunds"`
	TransactionCount int64 `json:"transaction_count"`
}

func (q *Queries) GetWeeklyWalletStats(ctx context.Context, arg GetWeeklyWalletStatsParams) (GetWeeklyWalletStatsRow, error) {
	row := q.db.QueryRow(ctx, getWeeklyWalletStats, arg.WalletID, arg.StartDate, arg.EndDate)
	var i GetWeeklyWalletStatsRow
	err := row.Scan(&i.TotalIncome, &i.TotalRefunds, &i.TransactionCount)
	return i, err
}
