// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package worker_db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// Moves OPEN -> CLOSED
	// Trigger: Current Time >= (Departure - Close Offset) OR Seats are 0
	AutoCloseTrips(ctx context.Context) error
	// Moves SCHEDULED -> OPEN
	// Trigger: Current Time >= (Departure - Open Offset)
	AutoOpenTrips(ctx context.Context) error
	CompleteJob(ctx context.Context, id uuid.UUID) error
	CreateJob(ctx context.Context, arg CreateJobParams) (uuid.UUID, error)
	FailJob(ctx context.Context, arg FailJobParams) error
	FetchNextJob(ctx context.Context) (GikiWalletJob, error)
	GetJobStats(ctx context.Context) (GetJobStatsRow, error)
	PruneCompletedJobs(ctx context.Context) error
	PruneExpiredTokens(ctx context.Context) error
}

var _ Querier = (*Queries)(nil)
