// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package worker_db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const autoCloseTrips = `-- name: AutoCloseTrips :exec
UPDATE giki_transport.trip
SET status = 'CLOSED', updated_at = NOW()
WHERE status = 'OPEN'
  AND (
    NOW() >= (departure_time - (booking_close_offset_minutes * INTERVAL '1 minute'))
        OR available_seats <= 0
)
`

// Moves OPEN -> CLOSED
// Trigger: Current Time >= (Departure - Close Offset) OR Seats are 0
func (q *Queries) AutoCloseTrips(ctx context.Context) error {
	_, err := q.db.Exec(ctx, autoCloseTrips)
	return err
}

const autoOpenTrips = `-- name: AutoOpenTrips :exec
UPDATE giki_transport.trip
SET status = 'OPEN', updated_at = NOW()
WHERE status = 'SCHEDULED'
  AND NOW() >= (departure_time - (booking_open_offset_minutes * INTERVAL '1 minute'))
`

// Moves SCHEDULED -> OPEN
// Trigger: Current Time >= (Departure - Open Offset)
func (q *Queries) AutoOpenTrips(ctx context.Context) error {
	_, err := q.db.Exec(ctx, autoOpenTrips)
	return err
}

const completeJob = `-- name: CompleteJob :exec
UPDATE giki_wallet.jobs
SET status = 'COMPLETED', updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CompleteJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, completeJob, id)
	return err
}

const createJob = `-- name: CreateJob :one
INSERT INTO giki_wallet.jobs (job_type, payload, run_at)
VALUES ($1, $2, $3)
RETURNING id
`

type CreateJobParams struct {
	JobType string    `json:"job_type"`
	Payload []byte    `json:"payload"`
	RunAt   time.Time `json:"run_at"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createJob, arg.JobType, arg.Payload, arg.RunAt)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const failJob = `-- name: FailJob :exec
UPDATE giki_wallet.jobs
SET status = CASE WHEN retry_count < max_retries THEN 'PENDING'::text ELSE 'FAILED'::text END,
    last_error = $2,
    retry_count = retry_count + 1,
    run_at = CASE
        WHEN retry_count < max_retries THEN NOW() + INTERVAL '1 minute'
        ELSE run_at
    END,
    updated_at = NOW()
WHERE id = $1
`

type FailJobParams struct {
	ID        uuid.UUID   `json:"id"`
	LastError pgtype.Text `json:"last_error"`
}

func (q *Queries) FailJob(ctx context.Context, arg FailJobParams) error {
	_, err := q.db.Exec(ctx, failJob, arg.ID, arg.LastError)
	return err
}

const fetchNextJob = `-- name: FetchNextJob :one
UPDATE giki_wallet.jobs
SET status = 'PROCESSING', updated_at = NOW()
WHERE id = (
    SELECT id
    FROM giki_wallet.jobs
    WHERE status = 'PENDING' AND run_at <= NOW()
    ORDER BY run_at ASC
    LIMIT 1
    FOR UPDATE SKIP LOCKED
)
RETURNING id, job_type, payload, status, run_at, retry_count, max_retries, last_error, created_at, updated_at
`

func (q *Queries) FetchNextJob(ctx context.Context) (GikiWalletJob, error) {
	row := q.db.QueryRow(ctx, fetchNextJob)
	var i GikiWalletJob
	err := row.Scan(
		&i.ID,
		&i.JobType,
		&i.Payload,
		&i.Status,
		&i.RunAt,
		&i.RetryCount,
		&i.MaxRetries,
		&i.LastError,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobStats = `-- name: GetJobStats :one
SELECT
    COUNT(*) FILTER (WHERE status = 'PENDING') as pending_count,
    COUNT(*) FILTER (WHERE status = 'PROCESSING') as processing_count,
    COUNT(*) FILTER (WHERE status = 'FAILED') as failed_count,
    COUNT(*) FILTER (WHERE status = 'COMPLETED' AND updated_at > NOW() - INTERVAL '1 hour') as completed_last_hour
FROM giki_wallet.jobs
`

type GetJobStatsRow struct {
	PendingCount      int64 `json:"pending_count"`
	ProcessingCount   int64 `json:"processing_count"`
	FailedCount       int64 `json:"failed_count"`
	CompletedLastHour int64 `json:"completed_last_hour"`
}

func (q *Queries) GetJobStats(ctx context.Context) (GetJobStatsRow, error) {
	row := q.db.QueryRow(ctx, getJobStats)
	var i GetJobStatsRow
	err := row.Scan(
		&i.PendingCount,
		&i.ProcessingCount,
		&i.FailedCount,
		&i.CompletedLastHour,
	)
	return i, err
}

const pruneCompletedJobs = `-- name: PruneCompletedJobs :exec
DELETE FROM giki_wallet.jobs
WHERE status = 'COMPLETED' AND updated_at < NOW() - INTERVAL '7 days'
`

func (q *Queries) PruneCompletedJobs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneCompletedJobs)
	return err
}

const pruneExpiredTokens = `-- name: PruneExpiredTokens :exec
DELETE FROM giki_wallet.access_tokens
WHERE expires_at < NOW() - INTERVAL '24 hours'
`

func (q *Queries) PruneExpiredTokens(ctx context.Context) error {
	_, err := q.db.Exec(ctx, pruneExpiredTokens)
	return err
}
