// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package payment_db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	// Mark transactions older than 24 hours that are still PENDING/UNKNOWN as FAILED.
	// These are permanently abandoned payments that will never resolve.
	AutoFailStalePendingTransactions(ctx context.Context) error
	ClearPollingStatus(ctx context.Context, txnRefNo string) error
	// =============================================================================
	// AUDIT LOG QUERIES
	// =============================================================================
	CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (GikiWalletPaymentAuditLog, error)
	CreateGatewayTransaction(ctx context.Context, arg CreateGatewayTransactionParams) (GikiWalletGatewayTransaction, error)
	ForceUpdateGatewayTransactionStatus(ctx context.Context, arg ForceUpdateGatewayTransactionStatusParams) (GikiWalletGatewayTransaction, error)
	GetAuditLogsByTxn(ctx context.Context, txnRefNo pgtype.Text) ([]GikiWalletPaymentAuditLog, error)
	GetByIdempotencyKey(ctx context.Context, idempotencyKey uuid.UUID) (GikiWalletGatewayTransaction, error)
	GetGatewayTransactionByRefDetailed(ctx context.Context, txnRefNo string) (GetGatewayTransactionByRefDetailedRow, error)
	GetGatewayTransactions(ctx context.Context, arg GetGatewayTransactionsParams) ([]GetGatewayTransactionsRow, error)
	GetGatewayTransactionsForExport(ctx context.Context, arg GetGatewayTransactionsForExportParams) ([]GetGatewayTransactionsForExportRow, error)
	GetPendingTransaction(ctx context.Context, userID uuid.UUID) (GikiWalletGatewayTransaction, error)
	// Fetch PENDING/UNKNOWN transactions between 3 minutes and 24 hours old,
	// not currently being polled, and not already having a pending RECONCILE_PAYMENT job.
	GetStalePendingTransactions(ctx context.Context) ([]GikiWalletGatewayTransaction, error)
	GetTransactionByTxnRefNo(ctx context.Context, txnRefNo string) (GikiWalletGatewayTransaction, error)
	GetUnprocessedAudits(ctx context.Context, arg GetUnprocessedAuditsParams) ([]GikiWalletPaymentAuditLog, error)
	MarkAuditFailed(ctx context.Context, arg MarkAuditFailedParams) error
	MarkAuditProcessed(ctx context.Context, id uuid.UUID) error
	UpdateGatewayTransactionStatus(ctx context.Context, arg UpdateGatewayTransactionStatusParams) error
	//- update polling status
	UpdatePollingStatus(ctx context.Context, txnRefNo string) (GikiWalletGatewayTransaction, error)
}

var _ Querier = (*Queries)(nil)
