// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package payment_db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const autoFailStalePendingTransactions = `-- name: AutoFailStalePendingTransactions :exec
UPDATE giki_wallet.gateway_transactions
SET status = 'FAILED',
    gateway_message = 'Automatically failed: payment abandoned after 24 hours',
    gateway_status_code = 'AUTO_FAILED',
    updated_at = NOW()
WHERE status IN ('PENDING', 'UNKNOWN')
  AND is_polling = FALSE
  AND created_at < NOW() - INTERVAL '24 hours'
`

// Mark transactions older than 24 hours that are still PENDING/UNKNOWN as FAILED.
// These are permanently abandoned payments that will never resolve.
func (q *Queries) AutoFailStalePendingTransactions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, autoFailStalePendingTransactions)
	return err
}

const clearPollingStatus = `-- name: ClearPollingStatus :exec
UPDATE giki_wallet.gateway_transactions
SET is_polling = FALSE
WHERE txn_ref_no = $1
`

func (q *Queries) ClearPollingStatus(ctx context.Context, txnRefNo string) error {
	_, err := q.db.Exec(ctx, clearPollingStatus, txnRefNo)
	return err
}

const createAuditLog = `-- name: CreateAuditLog :one

INSERT INTO giki_wallet.payment_audit_log (
    event_type, raw_payload, txn_ref_no, gateway_ref, user_id
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, event_type, raw_payload, txn_ref_no, gateway_ref, user_id, processed, processed_at, process_error, retry_count, received_at
`

type CreateAuditLogParams struct {
	EventType  GikiWalletAuditEventType `json:"event_type"`
	RawPayload []byte                   `json:"raw_payload"`
	TxnRefNo   pgtype.Text              `json:"txn_ref_no"`
	GatewayRef pgtype.Text              `json:"gateway_ref"`
	UserID     pgtype.UUID              `json:"user_id"`
}

// =============================================================================
// AUDIT LOG QUERIES
// =============================================================================
func (q *Queries) CreateAuditLog(ctx context.Context, arg CreateAuditLogParams) (GikiWalletPaymentAuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLog,
		arg.EventType,
		arg.RawPayload,
		arg.TxnRefNo,
		arg.GatewayRef,
		arg.UserID,
	)
	var i GikiWalletPaymentAuditLog
	err := row.Scan(
		&i.ID,
		&i.EventType,
		&i.RawPayload,
		&i.TxnRefNo,
		&i.GatewayRef,
		&i.UserID,
		&i.Processed,
		&i.ProcessedAt,
		&i.ProcessError,
		&i.RetryCount,
		&i.ReceivedAt,
	)
	return i, err
}

const createGatewayTransaction = `-- name: CreateGatewayTransaction :one
INSERT INTO giki_wallet.gateway_transactions(user_id, idempotency_key, bill_ref_id, txn_ref_no, payment_method, status, amount)
VALUES ($1, $2,$3,$4, $5, $6, $7)
RETURNING id, user_id, idempotency_key, bill_ref_id, txn_ref_no, payment_method, gateway_rrn, status, amount, raw_response, is_polling, created_at, updated_at, gateway_message, gateway_status_code
`

type CreateGatewayTransactionParams struct {
	UserID         uuid.UUID     `json:"user_id"`
	IdempotencyKey uuid.UUID     `json:"idempotency_key"`
	BillRefID      string        `json:"bill_ref_id"`
	TxnRefNo       string        `json:"txn_ref_no"`
	PaymentMethod  string        `json:"payment_method"`
	Status         CurrentStatus `json:"status"`
	Amount         int64         `json:"amount"`
}

func (q *Queries) CreateGatewayTransaction(ctx context.Context, arg CreateGatewayTransactionParams) (GikiWalletGatewayTransaction, error) {
	row := q.db.QueryRow(ctx, createGatewayTransaction,
		arg.UserID,
		arg.IdempotencyKey,
		arg.BillRefID,
		arg.TxnRefNo,
		arg.PaymentMethod,
		arg.Status,
		arg.Amount,
	)
	var i GikiWalletGatewayTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.BillRefID,
		&i.TxnRefNo,
		&i.PaymentMethod,
		&i.GatewayRrn,
		&i.Status,
		&i.Amount,
		&i.RawResponse,
		&i.IsPolling,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GatewayMessage,
		&i.GatewayStatusCode,
	)
	return i, err
}

const forceUpdateGatewayTransactionStatus = `-- name: ForceUpdateGatewayTransactionStatus :one
UPDATE giki_wallet.gateway_transactions
SET status = $1::current_status
WHERE txn_ref_no = $2
RETURNING id, user_id, idempotency_key, bill_ref_id, txn_ref_no, payment_method, gateway_rrn, status, amount, raw_response, is_polling, created_at, updated_at, gateway_message, gateway_status_code
`

type ForceUpdateGatewayTransactionStatusParams struct {
	Status   CurrentStatus `json:"status"`
	TxnRefNo string        `json:"txn_ref_no"`
}

func (q *Queries) ForceUpdateGatewayTransactionStatus(ctx context.Context, arg ForceUpdateGatewayTransactionStatusParams) (GikiWalletGatewayTransaction, error) {
	row := q.db.QueryRow(ctx, forceUpdateGatewayTransactionStatus, arg.Status, arg.TxnRefNo)
	var i GikiWalletGatewayTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.BillRefID,
		&i.TxnRefNo,
		&i.PaymentMethod,
		&i.GatewayRrn,
		&i.Status,
		&i.Amount,
		&i.RawResponse,
		&i.IsPolling,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GatewayMessage,
		&i.GatewayStatusCode,
	)
	return i, err
}

const getAuditLogsByTxn = `-- name: GetAuditLogsByTxn :many
SELECT id, event_type, raw_payload, txn_ref_no, gateway_ref, user_id, processed, processed_at, process_error, retry_count, received_at FROM giki_wallet.payment_audit_log
WHERE txn_ref_no = $1
ORDER BY received_at DESC
`

func (q *Queries) GetAuditLogsByTxn(ctx context.Context, txnRefNo pgtype.Text) ([]GikiWalletPaymentAuditLog, error) {
	rows, err := q.db.Query(ctx, getAuditLogsByTxn, txnRefNo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GikiWalletPaymentAuditLog
	for rows.Next() {
		var i GikiWalletPaymentAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.RawPayload,
			&i.TxnRefNo,
			&i.GatewayRef,
			&i.UserID,
			&i.Processed,
			&i.ProcessedAt,
			&i.ProcessError,
			&i.RetryCount,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getByIdempotencyKey = `-- name: GetByIdempotencyKey :one

SELECT id, user_id, idempotency_key, bill_ref_id, txn_ref_no, payment_method, gateway_rrn, status, amount, raw_response, is_polling, created_at, updated_at, gateway_message, gateway_status_code FROM giki_wallet.gateway_transactions
WHERE idempotency_key = $1
`

func (q *Queries) GetByIdempotencyKey(ctx context.Context, idempotencyKey uuid.UUID) (GikiWalletGatewayTransaction, error) {
	row := q.db.QueryRow(ctx, getByIdempotencyKey, idempotencyKey)
	var i GikiWalletGatewayTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.BillRefID,
		&i.TxnRefNo,
		&i.PaymentMethod,
		&i.GatewayRrn,
		&i.Status,
		&i.Amount,
		&i.RawResponse,
		&i.IsPolling,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GatewayMessage,
		&i.GatewayStatusCode,
	)
	return i, err
}

const getGatewayTransactionByRefDetailed = `-- name: GetGatewayTransactionByRefDetailed :one
SELECT 
    gt.txn_ref_no,
    gt.user_id,
    u.name as user_name,
    u.email as user_email,
    gt.amount,
    gt.status,
    gt.payment_method,
    gt.created_at,
    gt.updated_at,
    gt.bill_ref_id,
    gt.gateway_message,
    gt.gateway_status_code
FROM giki_wallet.gateway_transactions gt
JOIN giki_wallet.users u ON gt.user_id = u.id
WHERE gt.txn_ref_no = $1
`

type GetGatewayTransactionByRefDetailedRow struct {
	TxnRefNo          string        `json:"txn_ref_no"`
	UserID            uuid.UUID     `json:"user_id"`
	UserName          string        `json:"user_name"`
	UserEmail         string        `json:"user_email"`
	Amount            int64         `json:"amount"`
	Status            CurrentStatus `json:"status"`
	PaymentMethod     string        `json:"payment_method"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
	BillRefID         string        `json:"bill_ref_id"`
	GatewayMessage    pgtype.Text   `json:"gateway_message"`
	GatewayStatusCode pgtype.Text   `json:"gateway_status_code"`
}

func (q *Queries) GetGatewayTransactionByRefDetailed(ctx context.Context, txnRefNo string) (GetGatewayTransactionByRefDetailedRow, error) {
	row := q.db.QueryRow(ctx, getGatewayTransactionByRefDetailed, txnRefNo)
	var i GetGatewayTransactionByRefDetailedRow
	err := row.Scan(
		&i.TxnRefNo,
		&i.UserID,
		&i.UserName,
		&i.UserEmail,
		&i.Amount,
		&i.Status,
		&i.PaymentMethod,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BillRefID,
		&i.GatewayMessage,
		&i.GatewayStatusCode,
	)
	return i, err
}

const getGatewayTransactions = `-- name: GetGatewayTransactions :many
SELECT 
    gt.txn_ref_no,
    gt.user_id,
    u.name as user_name,
    u.email as user_email,
    gt.amount,
    gt.status,
    gt.payment_method,
    gt.created_at,
    gt.updated_at,
    gt.bill_ref_id,
    gt.gateway_message,
    gt.gateway_status_code,

    COUNT(*) OVER() as total_count,
    SUM(CASE WHEN gt.status = 'SUCCESS' THEN gt.amount ELSE 0 END) OVER() as total_amount
FROM giki_wallet.gateway_transactions gt

JOIN giki_wallet.users u ON gt.user_id = u.id
WHERE 
    (COALESCE($1::text, '') = '' OR gt.status::text = $1::text)
    AND (
        COALESCE($2::text, '') = '' OR 
        gt.payment_method = $2
    )
    AND gt.created_at >= $3
    AND gt.created_at <= $4
    AND (
        $5::text = '' OR
        gt.txn_ref_no ILIKE '%' || $5::text || '%' OR
        gt.bill_ref_id ILIKE '%' || $5::text || '%' OR
        u.name ILIKE '%' || $5::text || '%' OR
        u.email ILIKE '%' || $5::text || '%'
    )
ORDER BY gt.created_at DESC
LIMIT $7 OFFSET $6
`

type GetGatewayTransactionsParams struct {
	Status        pgtype.Text `json:"status"`
	PaymentMethod pgtype.Text `json:"payment_method"`
	StartDate     time.Time   `json:"start_date"`
	EndDate       time.Time   `json:"end_date"`
	Search        string      `json:"search"`
	Offset        int32       `json:"offset"`
	Limit         int32       `json:"limit"`
}

type GetGatewayTransactionsRow struct {
	TxnRefNo          string        `json:"txn_ref_no"`
	UserID            uuid.UUID     `json:"user_id"`
	UserName          string        `json:"user_name"`
	UserEmail         string        `json:"user_email"`
	Amount            int64         `json:"amount"`
	Status            CurrentStatus `json:"status"`
	PaymentMethod     string        `json:"payment_method"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
	BillRefID         string        `json:"bill_ref_id"`
	GatewayMessage    pgtype.Text   `json:"gateway_message"`
	GatewayStatusCode pgtype.Text   `json:"gateway_status_code"`
	TotalCount        int64         `json:"total_count"`
	TotalAmount       int64         `json:"total_amount"`
}

func (q *Queries) GetGatewayTransactions(ctx context.Context, arg GetGatewayTransactionsParams) ([]GetGatewayTransactionsRow, error) {
	rows, err := q.db.Query(ctx, getGatewayTransactions,
		arg.Status,
		arg.PaymentMethod,
		arg.StartDate,
		arg.EndDate,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGatewayTransactionsRow
	for rows.Next() {
		var i GetGatewayTransactionsRow
		if err := rows.Scan(
			&i.TxnRefNo,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.Amount,
			&i.Status,
			&i.PaymentMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BillRefID,
			&i.GatewayMessage,
			&i.GatewayStatusCode,
			&i.TotalCount,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getGatewayTransactionsForExport = `-- name: GetGatewayTransactionsForExport :many
SELECT 
    gt.txn_ref_no,
    gt.user_id,
    u.name as user_name,
    u.email as user_email,
    gt.amount,
    gt.status,
    gt.payment_method,
    gt.created_at,
    gt.updated_at,
    gt.bill_ref_id,
    gt.gateway_message,
    gt.gateway_status_code,

    COUNT(*) OVER() as total_count,
    SUM(CASE WHEN gt.status = 'SUCCESS' THEN gt.amount ELSE 0 END) OVER() as total_amount
FROM giki_wallet.gateway_transactions gt

JOIN giki_wallet.users u ON gt.user_id = u.id
WHERE 
    (COALESCE($1::text, '') = '' OR gt.status::text = $1::text)
    AND (
        COALESCE($2::text, '') = '' OR 
        gt.payment_method = $2
    )
    AND gt.created_at >= $3
    AND gt.created_at <= $4
    AND (
        $5::text = '' OR
        gt.txn_ref_no ILIKE '%' || $5::text || '%' OR
        gt.bill_ref_id ILIKE '%' || $5::text || '%' OR
        u.name ILIKE '%' || $5::text || '%' OR
        u.email ILIKE '%' || $5::text || '%'
    )
ORDER BY gt.created_at DESC
`

type GetGatewayTransactionsForExportParams struct {
	Status        pgtype.Text `json:"status"`
	PaymentMethod pgtype.Text `json:"payment_method"`
	StartDate     time.Time   `json:"start_date"`
	EndDate       time.Time   `json:"end_date"`
	Search        string      `json:"search"`
}

type GetGatewayTransactionsForExportRow struct {
	TxnRefNo          string        `json:"txn_ref_no"`
	UserID            uuid.UUID     `json:"user_id"`
	UserName          string        `json:"user_name"`
	UserEmail         string        `json:"user_email"`
	Amount            int64         `json:"amount"`
	Status            CurrentStatus `json:"status"`
	PaymentMethod     string        `json:"payment_method"`
	CreatedAt         time.Time     `json:"created_at"`
	UpdatedAt         time.Time     `json:"updated_at"`
	BillRefID         string        `json:"bill_ref_id"`
	GatewayMessage    pgtype.Text   `json:"gateway_message"`
	GatewayStatusCode pgtype.Text   `json:"gateway_status_code"`
	TotalCount        int64         `json:"total_count"`
	TotalAmount       int64         `json:"total_amount"`
}

func (q *Queries) GetGatewayTransactionsForExport(ctx context.Context, arg GetGatewayTransactionsForExportParams) ([]GetGatewayTransactionsForExportRow, error) {
	rows, err := q.db.Query(ctx, getGatewayTransactionsForExport,
		arg.Status,
		arg.PaymentMethod,
		arg.StartDate,
		arg.EndDate,
		arg.Search,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetGatewayTransactionsForExportRow
	for rows.Next() {
		var i GetGatewayTransactionsForExportRow
		if err := rows.Scan(
			&i.TxnRefNo,
			&i.UserID,
			&i.UserName,
			&i.UserEmail,
			&i.Amount,
			&i.Status,
			&i.PaymentMethod,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BillRefID,
			&i.GatewayMessage,
			&i.GatewayStatusCode,
			&i.TotalCount,
			&i.TotalAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingTransaction = `-- name: GetPendingTransaction :one

SELECT id, user_id, idempotency_key, bill_ref_id, txn_ref_no, payment_method, gateway_rrn, status, amount, raw_response, is_polling, created_at, updated_at, gateway_message, gateway_status_code FROM giki_wallet.gateway_transactions
WHERE user_id = $1
    AND status IN ('PENDING', 'UNKNOWN')
LIMIT 1
`

func (q *Queries) GetPendingTransaction(ctx context.Context, userID uuid.UUID) (GikiWalletGatewayTransaction, error) {
	row := q.db.QueryRow(ctx, getPendingTransaction, userID)
	var i GikiWalletGatewayTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.BillRefID,
		&i.TxnRefNo,
		&i.PaymentMethod,
		&i.GatewayRrn,
		&i.Status,
		&i.Amount,
		&i.RawResponse,
		&i.IsPolling,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GatewayMessage,
		&i.GatewayStatusCode,
	)
	return i, err
}

const getStalePendingTransactions = `-- name: GetStalePendingTransactions :many
SELECT gt.id, gt.user_id, gt.idempotency_key, gt.bill_ref_id, gt.txn_ref_no, gt.payment_method, gt.gateway_rrn, gt.status, gt.amount, gt.raw_response, gt.is_polling, gt.created_at, gt.updated_at, gt.gateway_message, gt.gateway_status_code FROM giki_wallet.gateway_transactions gt
WHERE gt.status IN ('PENDING', 'UNKNOWN')
  AND gt.is_polling = FALSE
  AND gt.created_at < NOW() - INTERVAL '3 minutes'
  AND gt.created_at > NOW() - INTERVAL '24 hours'
  AND NOT EXISTS (
    SELECT 1 FROM giki_wallet.jobs j
    WHERE j.job_type = 'RECONCILE_PAYMENT'
      AND j.status = 'PENDING'
      AND j.payload::jsonb->>'txn_ref_no' = gt.txn_ref_no
  )
ORDER BY gt.created_at ASC
`

// Fetch PENDING/UNKNOWN transactions between 3 minutes and 24 hours old,
// not currently being polled, and not already having a pending RECONCILE_PAYMENT job.
func (q *Queries) GetStalePendingTransactions(ctx context.Context) ([]GikiWalletGatewayTransaction, error) {
	rows, err := q.db.Query(ctx, getStalePendingTransactions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GikiWalletGatewayTransaction
	for rows.Next() {
		var i GikiWalletGatewayTransaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.IdempotencyKey,
			&i.BillRefID,
			&i.TxnRefNo,
			&i.PaymentMethod,
			&i.GatewayRrn,
			&i.Status,
			&i.Amount,
			&i.RawResponse,
			&i.IsPolling,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.GatewayMessage,
			&i.GatewayStatusCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransactionByTxnRefNo = `-- name: GetTransactionByTxnRefNo :one

SELECT id, user_id, idempotency_key, bill_ref_id, txn_ref_no, payment_method, gateway_rrn, status, amount, raw_response, is_polling, created_at, updated_at, gateway_message, gateway_status_code from giki_wallet.gateway_transactions
WHERE txn_ref_no = $1
`

func (q *Queries) GetTransactionByTxnRefNo(ctx context.Context, txnRefNo string) (GikiWalletGatewayTransaction, error) {
	row := q.db.QueryRow(ctx, getTransactionByTxnRefNo, txnRefNo)
	var i GikiWalletGatewayTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.BillRefID,
		&i.TxnRefNo,
		&i.PaymentMethod,
		&i.GatewayRrn,
		&i.Status,
		&i.Amount,
		&i.RawResponse,
		&i.IsPolling,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GatewayMessage,
		&i.GatewayStatusCode,
	)
	return i, err
}

const getUnprocessedAudits = `-- name: GetUnprocessedAudits :many
SELECT id, event_type, raw_payload, txn_ref_no, gateway_ref, user_id, processed, processed_at, process_error, retry_count, received_at FROM giki_wallet.payment_audit_log
WHERE processed = FALSE AND event_type = $1
ORDER BY received_at
LIMIT $2
`

type GetUnprocessedAuditsParams struct {
	EventType GikiWalletAuditEventType `json:"event_type"`
	Limit     int32                    `json:"limit"`
}

func (q *Queries) GetUnprocessedAudits(ctx context.Context, arg GetUnprocessedAuditsParams) ([]GikiWalletPaymentAuditLog, error) {
	rows, err := q.db.Query(ctx, getUnprocessedAudits, arg.EventType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GikiWalletPaymentAuditLog
	for rows.Next() {
		var i GikiWalletPaymentAuditLog
		if err := rows.Scan(
			&i.ID,
			&i.EventType,
			&i.RawPayload,
			&i.TxnRefNo,
			&i.GatewayRef,
			&i.UserID,
			&i.Processed,
			&i.ProcessedAt,
			&i.ProcessError,
			&i.RetryCount,
			&i.ReceivedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAuditFailed = `-- name: MarkAuditFailed :exec
UPDATE giki_wallet.payment_audit_log
SET process_error = $2, retry_count = retry_count + 1
WHERE id = $1
`

type MarkAuditFailedParams struct {
	ID           uuid.UUID   `json:"id"`
	ProcessError pgtype.Text `json:"process_error"`
}

func (q *Queries) MarkAuditFailed(ctx context.Context, arg MarkAuditFailedParams) error {
	_, err := q.db.Exec(ctx, markAuditFailed, arg.ID, arg.ProcessError)
	return err
}

const markAuditProcessed = `-- name: MarkAuditProcessed :exec
UPDATE giki_wallet.payment_audit_log
SET processed = TRUE, processed_at = NOW()
WHERE id = $1
`

func (q *Queries) MarkAuditProcessed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, markAuditProcessed, id)
	return err
}

const updateGatewayTransactionStatus = `-- name: UpdateGatewayTransactionStatus :exec
UPDATE giki_wallet.gateway_transactions 
SET status = $1::current_status, 
    gateway_message = $2, 
    gateway_status_code = $3,
    updated_at = NOW()
WHERE txn_ref_no = $4
`

type UpdateGatewayTransactionStatusParams struct {
	Status            CurrentStatus `json:"status"`
	GatewayMessage    pgtype.Text   `json:"gateway_message"`
	GatewayStatusCode pgtype.Text   `json:"gateway_status_code"`
	TxnRefNo          string        `json:"txn_ref_no"`
}

func (q *Queries) UpdateGatewayTransactionStatus(ctx context.Context, arg UpdateGatewayTransactionStatusParams) error {
	_, err := q.db.Exec(ctx, updateGatewayTransactionStatus,
		arg.Status,
		arg.GatewayMessage,
		arg.GatewayStatusCode,
		arg.TxnRefNo,
	)
	return err
}

const updatePollingStatus = `-- name: UpdatePollingStatus :one

UPDATE giki_wallet.gateway_transactions
SET is_polling = TRUE
WHERE txn_ref_no = $1 AND is_polling = FALSE
RETURNING id, user_id, idempotency_key, bill_ref_id, txn_ref_no, payment_method, gateway_rrn, status, amount, raw_response, is_polling, created_at, updated_at, gateway_message, gateway_status_code
`

// - update polling status
func (q *Queries) UpdatePollingStatus(ctx context.Context, txnRefNo string) (GikiWalletGatewayTransaction, error) {
	row := q.db.QueryRow(ctx, updatePollingStatus, txnRefNo)
	var i GikiWalletGatewayTransaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.IdempotencyKey,
		&i.BillRefID,
		&i.TxnRefNo,
		&i.PaymentMethod,
		&i.GatewayRrn,
		&i.Status,
		&i.Amount,
		&i.RawResponse,
		&i.IsPolling,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.GatewayMessage,
		&i.GatewayStatusCode,
	)
	return i, err
}
