// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package config_db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getConfig = `-- name: GetConfig :one
SELECT key, value, description, updated_at FROM giki_wallet.system_configs
WHERE key = $1
`

func (q *Queries) GetConfig(ctx context.Context, key string) (GikiWalletSystemConfig, error) {
	row := q.db.QueryRow(ctx, getConfig, key)
	var i GikiWalletSystemConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const listConfigs = `-- name: ListConfigs :many
SELECT key, value, description, updated_at FROM giki_wallet.system_configs
ORDER BY key ASC
`

func (q *Queries) ListConfigs(ctx context.Context) ([]GikiWalletSystemConfig, error) {
	rows, err := q.db.Query(ctx, listConfigs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GikiWalletSystemConfig
	for rows.Next() {
		var i GikiWalletSystemConfig
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateConfig = `-- name: UpdateConfig :one
UPDATE giki_wallet.system_configs
SET value = $2, updated_at = NOW()
WHERE key = $1
RETURNING key, value, description, updated_at
`

type UpdateConfigParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) UpdateConfig(ctx context.Context, arg UpdateConfigParams) (GikiWalletSystemConfig, error) {
	row := q.db.QueryRow(ctx, updateConfig, arg.Key, arg.Value)
	var i GikiWalletSystemConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertConfig = `-- name: UpsertConfig :one
INSERT INTO giki_wallet.system_configs (key, value, description)
VALUES ($1, $2, $3)
ON CONFLICT (key) DO UPDATE
SET value = $2, updated_at = NOW()
RETURNING key, value, description, updated_at
`

type UpsertConfigParams struct {
	Key         string      `json:"key"`
	Value       string      `json:"value"`
	Description pgtype.Text `json:"description"`
}

func (q *Queries) UpsertConfig(ctx context.Context, arg UpsertConfigParams) (GikiWalletSystemConfig, error) {
	row := q.db.QueryRow(ctx, upsertConfig, arg.Key, arg.Value, arg.Description)
	var i GikiWalletSystemConfig
	err := row.Scan(
		&i.Key,
		&i.Value,
		&i.Description,
		&i.UpdatedAt,
	)
	return i, err
}
