// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package config_db

import (
	"context"
)

type Querier interface {
	GetConfig(ctx context.Context, key string) (GikiWalletSystemConfig, error)
	ListConfigs(ctx context.Context) ([]GikiWalletSystemConfig, error)
	UpdateConfig(ctx context.Context, arg UpdateConfigParams) (GikiWalletSystemConfig, error)
	UpsertConfig(ctx context.Context, arg UpsertConfigParams) (GikiWalletSystemConfig, error)
}

var _ Querier = (*Queries)(nil)
