// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package transport_db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	BatchUpdateTripManualStatus(ctx context.Context, arg BatchUpdateTripManualStatusParams) error
	CancelTicketsByTripID(ctx context.Context, tripID uuid.UUID) error
	// =============================================
	// 4. TICKET CONFIRMATION (Finalizing)
	// =============================================
	ConfirmBookingWithDetails(ctx context.Context, arg ConfirmBookingWithDetailsParams) (ConfirmBookingWithDetailsRow, error)
	CreateBlankHold(ctx context.Context, arg CreateBlankHoldParams) (CreateBlankHoldRow, error)
	CreateTrip(ctx context.Context, arg CreateTripParams) (uuid.UUID, error)
	CreateTripStop(ctx context.Context, arg CreateTripStopParams) error
	// =============================================
	// 3. HOLD SYSTEM (Locking Seats)
	// =============================================
	DecreaseTripSeat(ctx context.Context, id uuid.UUID) (int32, error)
	DeleteAllActiveHoldsByUserID(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error)
	DeleteHold(ctx context.Context, id uuid.UUID) error
	DeleteTrip(ctx context.Context, id uuid.UUID) error
	GetActiveHoldsByUserID(ctx context.Context, userID uuid.UUID) ([]GetActiveHoldsByUserIDRow, error)
	// =============================================
	// 1. ROUTE & TRIP MANAGEMENT (Admin/System)
	// =============================================
	GetAllRoutes(ctx context.Context) ([]GetAllRoutesRow, error)
	GetConfirmedTicketsForTrip(ctx context.Context, tripID uuid.UUID) ([]GetConfirmedTicketsForTripRow, error)
	GetExpiredHolds(ctx context.Context) ([]GetExpiredHoldsRow, error)
	GetHold(ctx context.Context, id uuid.UUID) (GikiTransportTripHold, error)
	GetHoldForUpdate(ctx context.Context, id uuid.UUID) (GikiTransportTripHold, error)
	// =============================================
	// 2. QUOTA & RULES (Smart Logic)
	// =============================================
	GetQuotaRule(ctx context.Context, arg GetQuotaRuleParams) (GetQuotaRuleRow, error)
	GetRouteDetailsForTrip(ctx context.Context, id uuid.UUID) (GetRouteDetailsForTripRow, error)
	GetRouteStopsDetails(ctx context.Context, id uuid.UUID) ([]GetRouteStopsDetailsRow, error)
	GetRouteWeeklySchedule(ctx context.Context, routeID uuid.UUID) ([]GikiTransportRouteWeeklySchedule, error)
	GetTicketForCancellation(ctx context.Context, id uuid.UUID) (GetTicketForCancellationRow, error)
	GetTicketHistoryForAdmin(ctx context.Context, arg GetTicketHistoryForAdminParams) ([]GetTicketHistoryForAdminRow, error)
	// Admin query: Get confirmed tickets for a specific week and specific trip filters
	GetTicketsForAdmin(ctx context.Context, arg GetTicketsForAdminParams) ([]GetTicketsForAdminRow, error)
	GetTrip(ctx context.Context, id uuid.UUID) (GetTripRow, error)
	GetTripBookingCount(ctx context.Context, tripID uuid.UUID) (int64, error)
	GetTripForUpdate(ctx context.Context, id uuid.UUID) (uuid.UUID, error)
	GetTripInfoForExport(ctx context.Context, dollar_1 []uuid.UUID) ([]GetTripInfoForExportRow, error)
	GetTripPrice(ctx context.Context, id uuid.UUID) (int32, error)
	GetTripsForExport(ctx context.Context, dollar_1 []uuid.UUID) ([]GetTripsForExportRow, error)
	GetTripsForWeekWithStops(ctx context.Context, arg GetTripsForWeekWithStopsParams) ([]GetTripsForWeekWithStopsRow, error)
	GetUserEmailAndName(ctx context.Context, id uuid.UUID) (GetUserEmailAndNameRow, error)
	GetUserTicketsByID(ctx context.Context, userID uuid.UUID) ([]GetUserTicketsByIDRow, error)
	// Counts CONFIRMED tickets + ACTIVE HOLDS for the same calendar week (Mon-Sun) as the given reference time, for a specific direction.
	GetWeeklyTicketCountByDirection(ctx context.Context, arg GetWeeklyTicketCountByDirectionParams) (int64, error)
	GetWeeklyTicketStats(ctx context.Context, arg GetWeeklyTicketStatsParams) (GetWeeklyTicketStatsRow, error)
	// =============================================
	// 5. CANCELLATION & REAPER (Cleanup)
	// =============================================
	IncrementTripSeat(ctx context.Context, id uuid.UUID) error
	SetTicketCancelled(ctx context.Context, id uuid.UUID) error
	UpdateTrip(ctx context.Context, arg UpdateTripParams) error
	UpdateTripManualStatus(ctx context.Context, arg UpdateTripManualStatusParams) error
}

var _ Querier = (*Queries)(nil)
