// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package transport_db

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const batchUpdateTripManualStatus = `-- name: BatchUpdateTripManualStatus :exec
UPDATE giki_transport.trip
SET manual_status = $2, updated_at = NOW()
WHERE id = ANY($1::uuid[])
`

type BatchUpdateTripManualStatusParams struct {
	Column1      []uuid.UUID `json:"column_1"`
	ManualStatus pgtype.Text `json:"manual_status"`
}

func (q *Queries) BatchUpdateTripManualStatus(ctx context.Context, arg BatchUpdateTripManualStatusParams) error {
	_, err := q.db.Exec(ctx, batchUpdateTripManualStatus, arg.Column1, arg.ManualStatus)
	return err
}

const cancelTicketsByTripID = `-- name: CancelTicketsByTripID :exec
UPDATE giki_transport.tickets
SET status = 'CANCELLED_BY_ADMIN', updated_at = NOW()
WHERE trip_id = $1 AND status = 'CONFIRMED'
`

func (q *Queries) CancelTicketsByTripID(ctx context.Context, tripID uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelTicketsByTripID, tripID)
	return err
}

const confirmBookingWithDetails = `-- name: ConfirmBookingWithDetails :one


INSERT INTO giki_transport.tickets (
    trip_id, user_id, serial_no, ticket_code, pickup_stop_id, dropoff_stop_id,
    status, passenger_name, passenger_relation, price_paid
)
VALUES ($1, $2, COALESCE((SELECT MAX(serial_no) FROM giki_transport.tickets WHERE trip_id = $1), 0) + 1, $3, $4, $5, 'CONFIRMED', $6, $7, $8)
RETURNING id, serial_no, price_paid
`

type ConfirmBookingWithDetailsParams struct {
	TripID            uuid.UUID `json:"trip_id"`
	UserID            uuid.UUID `json:"user_id"`
	TicketCode        string    `json:"ticket_code"`
	PickupStopID      uuid.UUID `json:"pickup_stop_id"`
	DropoffStopID     uuid.UUID `json:"dropoff_stop_id"`
	PassengerName     string    `json:"passenger_name"`
	PassengerRelation string    `json:"passenger_relation"`
	PricePaid         int32     `json:"price_paid"`
}

type ConfirmBookingWithDetailsRow struct {
	ID        uuid.UUID `json:"id"`
	SerialNo  int32     `json:"serial_no"`
	PricePaid int32     `json:"price_paid"`
}

// =============================================
// 4. TICKET CONFIRMATION (Finalizing)
// =============================================
func (q *Queries) ConfirmBookingWithDetails(ctx context.Context, arg ConfirmBookingWithDetailsParams) (ConfirmBookingWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, confirmBookingWithDetails,
		arg.TripID,
		arg.UserID,
		arg.TicketCode,
		arg.PickupStopID,
		arg.DropoffStopID,
		arg.PassengerName,
		arg.PassengerRelation,
		arg.PricePaid,
	)
	var i ConfirmBookingWithDetailsRow
	err := row.Scan(&i.ID, &i.SerialNo, &i.PricePaid)
	return i, err
}

const createBlankHold = `-- name: CreateBlankHold :one

INSERT INTO giki_transport.trip_holds (
    trip_id, user_id, pickup_stop_id, dropoff_stop_id, expires_at
) VALUES ($1, $2, $3, $4, $5)
RETURNING id, expires_at
`

type CreateBlankHoldParams struct {
	TripID        uuid.UUID `json:"trip_id"`
	UserID        uuid.UUID `json:"user_id"`
	PickupStopID  uuid.UUID `json:"pickup_stop_id"`
	DropoffStopID uuid.UUID `json:"dropoff_stop_id"`
	ExpiresAt     time.Time `json:"expires_at"`
}

type CreateBlankHoldRow struct {
	ID        uuid.UUID `json:"id"`
	ExpiresAt time.Time `json:"expires_at"`
}

func (q *Queries) CreateBlankHold(ctx context.Context, arg CreateBlankHoldParams) (CreateBlankHoldRow, error) {
	row := q.db.QueryRow(ctx, createBlankHold,
		arg.TripID,
		arg.UserID,
		arg.PickupStopID,
		arg.DropoffStopID,
		arg.ExpiresAt,
	)
	var i CreateBlankHoldRow
	err := row.Scan(&i.ID, &i.ExpiresAt)
	return i, err
}

const createTrip = `-- name: CreateTrip :one
INSERT INTO giki_transport.trip(
    route_id,
    departure_time,
    booking_open_offset_minutes,
    booking_close_offset_minutes,
    total_capacity,
    available_seats,
    base_price,
    direction,
    bus_type
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type CreateTripParams struct {
	RouteID                   uuid.UUID `json:"route_id"`
	DepartureTime             time.Time `json:"departure_time"`
	BookingOpenOffsetMinutes  int32     `json:"booking_open_offset_minutes"`
	BookingCloseOffsetMinutes int32     `json:"booking_close_offset_minutes"`
	TotalCapacity             int32     `json:"total_capacity"`
	AvailableSeats            int32     `json:"available_seats"`
	BasePrice                 int32     `json:"base_price"`
	Direction                 string    `json:"direction"`
	BusType                   string    `json:"bus_type"`
}

func (q *Queries) CreateTrip(ctx context.Context, arg CreateTripParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createTrip,
		arg.RouteID,
		arg.DepartureTime,
		arg.BookingOpenOffsetMinutes,
		arg.BookingCloseOffsetMinutes,
		arg.TotalCapacity,
		arg.AvailableSeats,
		arg.BasePrice,
		arg.Direction,
		arg.BusType,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}

const createTripStop = `-- name: CreateTripStop :exec
INSERT INTO giki_transport.trip_stops (trip_id, stop_id, sequence_order)
VALUES ($1, $2, $3)
`

type CreateTripStopParams struct {
	TripID        uuid.UUID `json:"trip_id"`
	StopID        uuid.UUID `json:"stop_id"`
	SequenceOrder int32     `json:"sequence_order"`
}

func (q *Queries) CreateTripStop(ctx context.Context, arg CreateTripStopParams) error {
	_, err := q.db.Exec(ctx, createTripStop, arg.TripID, arg.StopID, arg.SequenceOrder)
	return err
}

const decreaseTripSeat = `-- name: DecreaseTripSeat :one


UPDATE giki_transport.trip
SET available_seats = available_seats - 1
WHERE id = $1 AND available_seats > 0
RETURNING available_seats
`

// =============================================
// 3. HOLD SYSTEM (Locking Seats)
// =============================================
func (q *Queries) DecreaseTripSeat(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, decreaseTripSeat, id)
	var available_seats int32
	err := row.Scan(&available_seats)
	return available_seats, err
}

const deleteAllActiveHoldsByUserID = `-- name: DeleteAllActiveHoldsByUserID :many
DELETE FROM giki_transport.trip_holds
WHERE user_id = $1 AND expires_at > NOW()
RETURNING trip_id
`

func (q *Queries) DeleteAllActiveHoldsByUserID(ctx context.Context, userID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, deleteAllActiveHoldsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var trip_id uuid.UUID
		if err := rows.Scan(&trip_id); err != nil {
			return nil, err
		}
		items = append(items, trip_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteHold = `-- name: DeleteHold :exec
DELETE FROM giki_transport.trip_holds WHERE id = $1
`

func (q *Queries) DeleteHold(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteHold, id)
	return err
}

const deleteTrip = `-- name: DeleteTrip :exec
DELETE FROM giki_transport.trip
WHERE id = $1
`

func (q *Queries) DeleteTrip(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteTrip, id)
	return err
}

const getActiveHoldsByUserID = `-- name: GetActiveHoldsByUserID :many
SELECT h.id, h.trip_id, h.expires_at, tr.direction, r.name as route_name
FROM giki_transport.trip_holds h
JOIN giki_transport.trip tr ON h.trip_id = tr.id
JOIN giki_transport.routes r ON tr.route_id = r.id
WHERE h.user_id = $1 AND h.expires_at > NOW()
`

type GetActiveHoldsByUserIDRow struct {
	ID        uuid.UUID `json:"id"`
	TripID    uuid.UUID `json:"trip_id"`
	ExpiresAt time.Time `json:"expires_at"`
	Direction string    `json:"direction"`
	RouteName string    `json:"route_name"`
}

func (q *Queries) GetActiveHoldsByUserID(ctx context.Context, userID uuid.UUID) ([]GetActiveHoldsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, getActiveHoldsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveHoldsByUserIDRow
	for rows.Next() {
		var i GetActiveHoldsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.TripID,
			&i.ExpiresAt,
			&i.Direction,
			&i.RouteName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllRoutes = `-- name: GetAllRoutes :many

SELECT id, name FROM giki_transport.routes
WHERE is_active = TRUE
ORDER BY name ASC
`

type GetAllRoutesRow struct {
	ID   uuid.UUID `json:"id"`
	Name string    `json:"name"`
}

// =============================================
// 1. ROUTE & TRIP MANAGEMENT (Admin/System)
// =============================================
func (q *Queries) GetAllRoutes(ctx context.Context) ([]GetAllRoutesRow, error) {
	rows, err := q.db.Query(ctx, getAllRoutes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllRoutesRow
	for rows.Next() {
		var i GetAllRoutesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfirmedTicketsForTrip = `-- name: GetConfirmedTicketsForTrip :many
SELECT 
    t.id as ticket_id,
    t.user_id,
    t.ticket_code,
    t.passenger_name,
    t.price_paid as base_price,
    r.name as route_name
FROM giki_transport.tickets t
JOIN giki_transport.trip tr ON t.trip_id = tr.id
JOIN giki_transport.routes r ON tr.route_id = r.id
WHERE t.trip_id = $1 AND t.status = 'CONFIRMED'
`

type GetConfirmedTicketsForTripRow struct {
	TicketID      uuid.UUID `json:"ticket_id"`
	UserID        uuid.UUID `json:"user_id"`
	TicketCode    string    `json:"ticket_code"`
	PassengerName string    `json:"passenger_name"`
	BasePrice     int32     `json:"base_price"`
	RouteName     string    `json:"route_name"`
}

func (q *Queries) GetConfirmedTicketsForTrip(ctx context.Context, tripID uuid.UUID) ([]GetConfirmedTicketsForTripRow, error) {
	rows, err := q.db.Query(ctx, getConfirmedTicketsForTrip, tripID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetConfirmedTicketsForTripRow
	for rows.Next() {
		var i GetConfirmedTicketsForTripRow
		if err := rows.Scan(
			&i.TicketID,
			&i.UserID,
			&i.TicketCode,
			&i.PassengerName,
			&i.BasePrice,
			&i.RouteName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredHolds = `-- name: GetExpiredHolds :many

SELECT id, trip_id FROM giki_transport.trip_holds
WHERE expires_at < NOW()
FOR UPDATE SKIP LOCKED LIMIT 50
`

type GetExpiredHoldsRow struct {
	ID     uuid.UUID `json:"id"`
	TripID uuid.UUID `json:"trip_id"`
}

func (q *Queries) GetExpiredHolds(ctx context.Context) ([]GetExpiredHoldsRow, error) {
	rows, err := q.db.Query(ctx, getExpiredHolds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiredHoldsRow
	for rows.Next() {
		var i GetExpiredHoldsRow
		if err := rows.Scan(&i.ID, &i.TripID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getHold = `-- name: GetHold :one
SELECT id, trip_id, user_id, pickup_stop_id, dropoff_stop_id, passenger_name, passenger_relation, expires_at, created_at FROM giki_transport.trip_holds WHERE id = $1
`

func (q *Queries) GetHold(ctx context.Context, id uuid.UUID) (GikiTransportTripHold, error) {
	row := q.db.QueryRow(ctx, getHold, id)
	var i GikiTransportTripHold
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.PickupStopID,
		&i.DropoffStopID,
		&i.PassengerName,
		&i.PassengerRelation,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getHoldForUpdate = `-- name: GetHoldForUpdate :one
SELECT id, trip_id, user_id, pickup_stop_id, dropoff_stop_id, passenger_name, passenger_relation, expires_at, created_at FROM giki_transport.trip_holds WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetHoldForUpdate(ctx context.Context, id uuid.UUID) (GikiTransportTripHold, error) {
	row := q.db.QueryRow(ctx, getHoldForUpdate, id)
	var i GikiTransportTripHold
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.PickupStopID,
		&i.DropoffStopID,
		&i.PassengerName,
		&i.PassengerRelation,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getQuotaRule = `-- name: GetQuotaRule :one

SELECT weekly_limit, allow_dependent_booking
FROM giki_transport.quota_rules
WHERE user_role = $1 AND direction = $2
`

type GetQuotaRuleParams struct {
	UserRole  string `json:"user_role"`
	Direction string `json:"direction"`
}

type GetQuotaRuleRow struct {
	WeeklyLimit           int32 `json:"weekly_limit"`
	AllowDependentBooking bool  `json:"allow_dependent_booking"`
}

// =============================================
// 2. QUOTA & RULES (Smart Logic)
// =============================================
func (q *Queries) GetQuotaRule(ctx context.Context, arg GetQuotaRuleParams) (GetQuotaRuleRow, error) {
	row := q.db.QueryRow(ctx, getQuotaRule, arg.UserRole, arg.Direction)
	var i GetQuotaRuleRow
	err := row.Scan(&i.WeeklyLimit, &i.AllowDependentBooking)
	return i, err
}

const getRouteDetailsForTrip = `-- name: GetRouteDetailsForTrip :one
SELECT r.name as route_name, tr.direction
FROM giki_transport.trip tr
JOIN giki_transport.routes r ON tr.route_id = r.id
WHERE tr.id = $1
`

type GetRouteDetailsForTripRow struct {
	RouteName string `json:"route_name"`
	Direction string `json:"direction"`
}

func (q *Queries) GetRouteDetailsForTrip(ctx context.Context, id uuid.UUID) (GetRouteDetailsForTripRow, error) {
	row := q.db.QueryRow(ctx, getRouteDetailsForTrip, id)
	var i GetRouteDetailsForTripRow
	err := row.Scan(&i.RouteName, &i.Direction)
	return i, err
}

const getRouteStopsDetails = `-- name: GetRouteStopsDetails :many
SELECT

    r.id as route_id, r.name as route_name,
    r.default_booking_open_offset_minutes,
    r.default_booking_close_offset_minutes,

    s.id as stop_id, s.address as stop_name,

    rms.default_sequence_order,
    rms.is_default_active

FROM giki_transport.routes as r
JOIN giki_transport.route_master_stops as rms ON r.id = rms.route_id
JOIN giki_transport.stops as s ON rms.stop_id = s.id
WHERE r.id = $1
ORDER BY rms.default_sequence_order ASC
`

type GetRouteStopsDetailsRow struct {
	RouteID                          uuid.UUID   `json:"route_id"`
	RouteName                        string      `json:"route_name"`
	DefaultBookingOpenOffsetMinutes  pgtype.Int4 `json:"default_booking_open_offset_minutes"`
	DefaultBookingCloseOffsetMinutes pgtype.Int4 `json:"default_booking_close_offset_minutes"`
	StopID                           uuid.UUID   `json:"stop_id"`
	StopName                         string      `json:"stop_name"`
	DefaultSequenceOrder             int32       `json:"default_sequence_order"`
	IsDefaultActive                  bool        `json:"is_default_active"`
}

func (q *Queries) GetRouteStopsDetails(ctx context.Context, id uuid.UUID) ([]GetRouteStopsDetailsRow, error) {
	rows, err := q.db.Query(ctx, getRouteStopsDetails, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRouteStopsDetailsRow
	for rows.Next() {
		var i GetRouteStopsDetailsRow
		if err := rows.Scan(
			&i.RouteID,
			&i.RouteName,
			&i.DefaultBookingOpenOffsetMinutes,
			&i.DefaultBookingCloseOffsetMinutes,
			&i.StopID,
			&i.StopName,
			&i.DefaultSequenceOrder,
			&i.IsDefaultActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRouteWeeklySchedule = `-- name: GetRouteWeeklySchedule :many

SELECT id, route_id, day_of_week, departure_time, created_at
FROM giki_transport.route_weekly_schedules
WHERE route_id = $1
ORDER BY day_of_week ASC, departure_time ASC
`

func (q *Queries) GetRouteWeeklySchedule(ctx context.Context, routeID uuid.UUID) ([]GikiTransportRouteWeeklySchedule, error) {
	rows, err := q.db.Query(ctx, getRouteWeeklySchedule, routeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GikiTransportRouteWeeklySchedule
	for rows.Next() {
		var i GikiTransportRouteWeeklySchedule
		if err := rows.Scan(
			&i.ID,
			&i.RouteID,
			&i.DayOfWeek,
			&i.DepartureTime,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketForCancellation = `-- name: GetTicketForCancellation :one
SELECT
    t.id, t.trip_id, t.user_id, t.status, t.price_paid as base_price
FROM giki_transport.tickets t
         JOIN giki_transport.trip tr ON t.trip_id = tr.id
WHERE t.id = $1
  AND t.status = 'CONFIRMED'
  -- LOGIC: Allow cancel ONLY IF Current Time < (Departure - Close Offset)
  AND NOW() < (tr.departure_time - (tr.booking_close_offset_minutes * INTERVAL '1 minute'))
`

type GetTicketForCancellationRow struct {
	ID        uuid.UUID `json:"id"`
	TripID    uuid.UUID `json:"trip_id"`
	UserID    uuid.UUID `json:"user_id"`
	Status    string    `json:"status"`
	BasePrice int32     `json:"base_price"`
}

func (q *Queries) GetTicketForCancellation(ctx context.Context, id uuid.UUID) (GetTicketForCancellationRow, error) {
	row := q.db.QueryRow(ctx, getTicketForCancellation, id)
	var i GetTicketForCancellationRow
	err := row.Scan(
		&i.ID,
		&i.TripID,
		&i.UserID,
		&i.Status,
		&i.BasePrice,
	)
	return i, err
}

const getTicketHistoryForAdmin = `-- name: GetTicketHistoryForAdmin :many
SELECT
    t.id as ticket_id,
    t.serial_no,
    t.ticket_code,
    t.passenger_name,
    t.passenger_relation,
    t.status as ticket_status,
    t.booking_time,
    t.updated_at as status_updated_at,
    u.name as user_name,
    u.email as user_email,
    tr.id as trip_id,
    tr.departure_time,
    tr.bus_type,
    tr.direction,
    r.name as route_name,
    s_pickup.address as pickup_location,
    s_dropoff.address as dropoff_location,
    t.price_paid as price,
    COUNT(*) OVER() as total_count
FROM giki_transport.tickets t
JOIN giki_transport.trip tr ON t.trip_id = tr.id
JOIN giki_transport.routes r ON tr.route_id = r.id
JOIN giki_wallet.users u ON t.user_id = u.id
JOIN giki_transport.stops s_pickup ON t.pickup_stop_id = s_pickup.id
JOIN giki_transport.stops s_dropoff ON t.dropoff_stop_id = s_dropoff.id
WHERE
    t.status != 'CONFIRMED'
ORDER BY t.updated_at DESC
LIMIT $1 OFFSET $2
`

type GetTicketHistoryForAdminParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

type GetTicketHistoryForAdminRow struct {
	TicketID          uuid.UUID `json:"ticket_id"`
	SerialNo          int32     `json:"serial_no"`
	TicketCode        string    `json:"ticket_code"`
	PassengerName     string    `json:"passenger_name"`
	PassengerRelation string    `json:"passenger_relation"`
	TicketStatus      string    `json:"ticket_status"`
	BookingTime       time.Time `json:"booking_time"`
	StatusUpdatedAt   time.Time `json:"status_updated_at"`
	UserName          string    `json:"user_name"`
	UserEmail         string    `json:"user_email"`
	TripID            uuid.UUID `json:"trip_id"`
	DepartureTime     time.Time `json:"departure_time"`
	BusType           string    `json:"bus_type"`
	Direction         string    `json:"direction"`
	RouteName         string    `json:"route_name"`
	PickupLocation    string    `json:"pickup_location"`
	DropoffLocation   string    `json:"dropoff_location"`
	Price             int32     `json:"price"`
	TotalCount        int64     `json:"total_count"`
}

func (q *Queries) GetTicketHistoryForAdmin(ctx context.Context, arg GetTicketHistoryForAdminParams) ([]GetTicketHistoryForAdminRow, error) {
	rows, err := q.db.Query(ctx, getTicketHistoryForAdmin, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTicketHistoryForAdminRow
	for rows.Next() {
		var i GetTicketHistoryForAdminRow
		if err := rows.Scan(
			&i.TicketID,
			&i.SerialNo,
			&i.TicketCode,
			&i.PassengerName,
			&i.PassengerRelation,
			&i.TicketStatus,
			&i.BookingTime,
			&i.StatusUpdatedAt,
			&i.UserName,
			&i.UserEmail,
			&i.TripID,
			&i.DepartureTime,
			&i.BusType,
			&i.Direction,
			&i.RouteName,
			&i.PickupLocation,
			&i.DropoffLocation,
			&i.Price,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicketsForAdmin = `-- name: GetTicketsForAdmin :many
SELECT
    t.id as ticket_id,
    t.serial_no,
    t.ticket_code,
    t.passenger_name,
    t.passenger_relation,
    t.status as ticket_status,
    t.booking_time,
    u.name as user_name,
    u.email as user_email,
    tr.id as trip_id,
    tr.departure_time,
    tr.bus_type,
    tr.direction,
    r.name as route_name,
    s_pickup.address as pickup_location,
    s_dropoff.address as dropoff_location,
    t.price_paid as price,
    COUNT(*) OVER() as total_count
FROM giki_transport.tickets t
JOIN giki_transport.trip tr ON t.trip_id = tr.id
JOIN giki_transport.routes r ON tr.route_id = r.id
JOIN giki_wallet.users u ON t.user_id = u.id
JOIN giki_transport.stops s_pickup ON t.pickup_stop_id = s_pickup.id
JOIN giki_transport.stops s_dropoff ON t.dropoff_stop_id = s_dropoff.id
WHERE
    tr.departure_time >= $1
    AND tr.departure_time < $2
    AND ($3::text = '' OR UPPER(tr.bus_type) = UPPER($3::text))
    AND ($4::text = '' OR t.status = $4::text)
    AND (
        $5::text = '' OR
        t.ticket_code ILIKE '%' || $5::text || '%' OR
        t.passenger_name ILIKE '%' || $5::text || '%' OR
        u.name ILIKE '%' || $5::text || '%' OR
        u.email ILIKE '%' || $5::text || '%'
    )
ORDER BY tr.departure_time ASC, t.serial_no ASC
LIMIT $7 OFFSET $6
`

type GetTicketsForAdminParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
	BusType   string    `json:"bus_type"`
	Status    string    `json:"status"`
	Search    string    `json:"search"`
	Offset    int32     `json:"offset"`
	Limit     int32     `json:"limit"`
}

type GetTicketsForAdminRow struct {
	TicketID          uuid.UUID `json:"ticket_id"`
	SerialNo          int32     `json:"serial_no"`
	TicketCode        string    `json:"ticket_code"`
	PassengerName     string    `json:"passenger_name"`
	PassengerRelation string    `json:"passenger_relation"`
	TicketStatus      string    `json:"ticket_status"`
	BookingTime       time.Time `json:"booking_time"`
	UserName          string    `json:"user_name"`
	UserEmail         string    `json:"user_email"`
	TripID            uuid.UUID `json:"trip_id"`
	DepartureTime     time.Time `json:"departure_time"`
	BusType           string    `json:"bus_type"`
	Direction         string    `json:"direction"`
	RouteName         string    `json:"route_name"`
	PickupLocation    string    `json:"pickup_location"`
	DropoffLocation   string    `json:"dropoff_location"`
	Price             int32     `json:"price"`
	TotalCount        int64     `json:"total_count"`
}

// Admin query: Get confirmed tickets for a specific week and specific trip filters
func (q *Queries) GetTicketsForAdmin(ctx context.Context, arg GetTicketsForAdminParams) ([]GetTicketsForAdminRow, error) {
	rows, err := q.db.Query(ctx, getTicketsForAdmin,
		arg.StartDate,
		arg.EndDate,
		arg.BusType,
		arg.Status,
		arg.Search,
		arg.Offset,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTicketsForAdminRow
	for rows.Next() {
		var i GetTicketsForAdminRow
		if err := rows.Scan(
			&i.TicketID,
			&i.SerialNo,
			&i.TicketCode,
			&i.PassengerName,
			&i.PassengerRelation,
			&i.TicketStatus,
			&i.BookingTime,
			&i.UserName,
			&i.UserEmail,
			&i.TripID,
			&i.DepartureTime,
			&i.BusType,
			&i.Direction,
			&i.RouteName,
			&i.PickupLocation,
			&i.DropoffLocation,
			&i.Price,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrip = `-- name: GetTrip :one
SELECT
    t.id, t.route_id, t.driver_id, t.departure_time, t.booking_open_offset_minutes, t.booking_close_offset_minutes, t.direction, t.base_price, t.bus_type, t.total_capacity, t.available_seats, t.status, t.created_at, t.updated_at, t.manual_status,
    CASE
        WHEN t.manual_status = 'CANCELLED' THEN 'CANCELLED'
        WHEN t.available_seats <= 0 THEN 'FULL'
        WHEN t.manual_status = 'CLOSED' THEN 'CLOSED'
        WHEN t.manual_status = 'OPEN' THEN 'OPEN'
        WHEN NOW() >= (t.departure_time - (t.booking_close_offset_minutes * INTERVAL '1 minute')) THEN 'CLOSED'
        WHEN NOW() < (t.departure_time - (t.booking_open_offset_minutes * INTERVAL '1 minute')) THEN 'SCHEDULED'
        ELSE 'OPEN'
    END::TEXT as computed_status
FROM giki_transport.trip t
WHERE id = $1
`

type GetTripRow struct {
	ID                        uuid.UUID   `json:"id"`
	RouteID                   uuid.UUID   `json:"route_id"`
	DriverID                  pgtype.UUID `json:"driver_id"`
	DepartureTime             time.Time   `json:"departure_time"`
	BookingOpenOffsetMinutes  int32       `json:"booking_open_offset_minutes"`
	BookingCloseOffsetMinutes int32       `json:"booking_close_offset_minutes"`
	Direction                 string      `json:"direction"`
	BasePrice                 int32       `json:"base_price"`
	BusType                   string      `json:"bus_type"`
	TotalCapacity             int32       `json:"total_capacity"`
	AvailableSeats            int32       `json:"available_seats"`
	Status                    pgtype.Text `json:"status"`
	CreatedAt                 time.Time   `json:"created_at"`
	UpdatedAt                 time.Time   `json:"updated_at"`
	ManualStatus              pgtype.Text `json:"manual_status"`
	ComputedStatus            string      `json:"computed_status"`
}

func (q *Queries) GetTrip(ctx context.Context, id uuid.UUID) (GetTripRow, error) {
	row := q.db.QueryRow(ctx, getTrip, id)
	var i GetTripRow
	err := row.Scan(
		&i.ID,
		&i.RouteID,
		&i.DriverID,
		&i.DepartureTime,
		&i.BookingOpenOffsetMinutes,
		&i.BookingCloseOffsetMinutes,
		&i.Direction,
		&i.BasePrice,
		&i.BusType,
		&i.TotalCapacity,
		&i.AvailableSeats,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ManualStatus,
		&i.ComputedStatus,
	)
	return i, err
}

const getTripBookingCount = `-- name: GetTripBookingCount :one
SELECT COUNT(*) as booking_count
FROM giki_transport.tickets
WHERE trip_id = $1 AND status = 'CONFIRMED'
`

func (q *Queries) GetTripBookingCount(ctx context.Context, tripID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getTripBookingCount, tripID)
	var booking_count int64
	err := row.Scan(&booking_count)
	return booking_count, err
}

const getTripForUpdate = `-- name: GetTripForUpdate :one
SELECT id FROM giki_transport.trip WHERE id = $1 FOR UPDATE
`

func (q *Queries) GetTripForUpdate(ctx context.Context, id uuid.UUID) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, getTripForUpdate, id)
	err := row.Scan(&id)
	return id, err
}

const getTripInfoForExport = `-- name: GetTripInfoForExport :many
SELECT
    t.id as trip_id,
    r.name as route_name,
    t.departure_time,
    t.bus_type,
    t.direction
FROM giki_transport.trip t
JOIN giki_transport.routes r ON t.route_id = r.id
WHERE t.id = ANY($1::uuid[])
ORDER BY t.departure_time
`

type GetTripInfoForExportRow struct {
	TripID        uuid.UUID `json:"trip_id"`
	RouteName     string    `json:"route_name"`
	DepartureTime time.Time `json:"departure_time"`
	BusType       string    `json:"bus_type"`
	Direction     string    `json:"direction"`
}

func (q *Queries) GetTripInfoForExport(ctx context.Context, dollar_1 []uuid.UUID) ([]GetTripInfoForExportRow, error) {
	rows, err := q.db.Query(ctx, getTripInfoForExport, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTripInfoForExportRow
	for rows.Next() {
		var i GetTripInfoForExportRow
		if err := rows.Scan(
			&i.TripID,
			&i.RouteName,
			&i.DepartureTime,
			&i.BusType,
			&i.Direction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTripPrice = `-- name: GetTripPrice :one
SELECT base_price FROM giki_transport.trip WHERE id = $1
`

func (q *Queries) GetTripPrice(ctx context.Context, id uuid.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getTripPrice, id)
	var base_price int32
	err := row.Scan(&base_price)
	return base_price, err
}

const getTripsForExport = `-- name: GetTripsForExport :many
SELECT
    t.id as trip_id,
    r.name as route_name,
    t.departure_time,
    t.bus_type,
    t.direction,
    ti.serial_no,
    ti.ticket_code,
    ti.passenger_name,
    u.phone_number as user_phone_number,
    u.email as user_email,
    s.address as stop_name,
    COALESCE(ts.sequence_order, 999) as stop_sequence
FROM giki_transport.trip t
JOIN giki_transport.routes r ON t.route_id = r.id
JOIN giki_transport.tickets ti ON t.id = ti.trip_id AND ti.status = 'CONFIRMED'
JOIN giki_transport.stops s ON ti.pickup_stop_id = s.id
JOIN giki_wallet.users u ON ti.user_id = u.id
LEFT JOIN giki_transport.trip_stops ts ON (t.id = ts.trip_id AND s.id = ts.stop_id)
WHERE t.id = ANY($1::uuid[])
ORDER BY t.id, COALESCE(ts.sequence_order, 999), ti.serial_no
`

type GetTripsForExportRow struct {
	TripID          uuid.UUID `json:"trip_id"`
	RouteName       string    `json:"route_name"`
	DepartureTime   time.Time `json:"departure_time"`
	BusType         string    `json:"bus_type"`
	Direction       string    `json:"direction"`
	SerialNo        int32     `json:"serial_no"`
	TicketCode      string    `json:"ticket_code"`
	PassengerName   string    `json:"passenger_name"`
	UserPhoneNumber string    `json:"user_phone_number"`
	UserEmail       string    `json:"user_email"`
	StopName        string    `json:"stop_name"`
	StopSequence    int32     `json:"stop_sequence"`
}

func (q *Queries) GetTripsForExport(ctx context.Context, dollar_1 []uuid.UUID) ([]GetTripsForExportRow, error) {
	rows, err := q.db.Query(ctx, getTripsForExport, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTripsForExportRow
	for rows.Next() {
		var i GetTripsForExportRow
		if err := rows.Scan(
			&i.TripID,
			&i.RouteName,
			&i.DepartureTime,
			&i.BusType,
			&i.Direction,
			&i.SerialNo,
			&i.TicketCode,
			&i.PassengerName,
			&i.UserPhoneNumber,
			&i.UserEmail,
			&i.StopName,
			&i.StopSequence,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTripsForWeekWithStops = `-- name: GetTripsForWeekWithStops :many

SELECT
    t.id as trip_id,
    r.id as route_id,
    r.name as route_name,
    t.direction,
    t.bus_type,
    t.departure_time,
    (t.departure_time - (t.booking_open_offset_minutes * INTERVAL '1 minute'))::TIMESTAMPTZ as booking_opens_at,
    (t.departure_time - (t.booking_close_offset_minutes * INTERVAL '1 minute'))::TIMESTAMPTZ as booking_closes_at,
    
    -- Dynamic Status Calculation
    CASE
        WHEN t.manual_status = 'CANCELLED' THEN 'CANCELLED'
        WHEN t.available_seats <= 0 THEN 'FULL'
        WHEN t.manual_status = 'CLOSED' THEN 'CLOSED'
        WHEN t.manual_status = 'OPEN' THEN 'OPEN'
        WHEN NOW() >= (t.departure_time - (t.booking_close_offset_minutes * INTERVAL '1 minute')) THEN 'CLOSED'
        WHEN NOW() < (t.departure_time - (t.booking_open_offset_minutes * INTERVAL '1 minute')) THEN 'SCHEDULED'
        ELSE 'OPEN'
    END as status,
    
    t.manual_status,
    t.available_seats,
    t.total_capacity,
    t.base_price,
    (
        SELECT COALESCE(JSON_AGG(
            JSON_BUILD_OBJECT(
                'stop_id', s.id,
                'stop_name', s.address,
                'sequence', ts.sequence_order
            ) ORDER BY ts.sequence_order ASC
        ), '[]')::text
        FROM giki_transport.trip_stops ts
        JOIN giki_transport.stops s ON ts.stop_id = s.id
        WHERE ts.trip_id = t.id
    ) as stops_json
FROM giki_transport.trip t
JOIN giki_transport.routes r ON t.route_id = r.id
WHERE
    t.departure_time >= $1
    AND t.departure_time < $2
    AND t.status IS DISTINCT FROM 'DELETED'
ORDER BY t.departure_time ASC
`

type GetTripsForWeekWithStopsParams struct {
	DepartureTime   time.Time `json:"departure_time"`
	DepartureTime_2 time.Time `json:"departure_time_2"`
}

type GetTripsForWeekWithStopsRow struct {
	TripID          uuid.UUID   `json:"trip_id"`
	RouteID         uuid.UUID   `json:"route_id"`
	RouteName       string      `json:"route_name"`
	Direction       string      `json:"direction"`
	BusType         string      `json:"bus_type"`
	DepartureTime   time.Time   `json:"departure_time"`
	BookingOpensAt  time.Time   `json:"booking_opens_at"`
	BookingClosesAt time.Time   `json:"booking_closes_at"`
	Status          string      `json:"status"`
	ManualStatus    pgtype.Text `json:"manual_status"`
	AvailableSeats  int32       `json:"available_seats"`
	TotalCapacity   int32       `json:"total_capacity"`
	BasePrice       int32       `json:"base_price"`
	StopsJson       string      `json:"stops_json"`
}

func (q *Queries) GetTripsForWeekWithStops(ctx context.Context, arg GetTripsForWeekWithStopsParams) ([]GetTripsForWeekWithStopsRow, error) {
	rows, err := q.db.Query(ctx, getTripsForWeekWithStops, arg.DepartureTime, arg.DepartureTime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTripsForWeekWithStopsRow
	for rows.Next() {
		var i GetTripsForWeekWithStopsRow
		if err := rows.Scan(
			&i.TripID,
			&i.RouteID,
			&i.RouteName,
			&i.Direction,
			&i.BusType,
			&i.DepartureTime,
			&i.BookingOpensAt,
			&i.BookingClosesAt,
			&i.Status,
			&i.ManualStatus,
			&i.AvailableSeats,
			&i.TotalCapacity,
			&i.BasePrice,
			&i.StopsJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserEmailAndName = `-- name: GetUserEmailAndName :one
SELECT name, email FROM giki_wallet.users WHERE id = $1
`

type GetUserEmailAndNameRow struct {
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) GetUserEmailAndName(ctx context.Context, id uuid.UUID) (GetUserEmailAndNameRow, error) {
	row := q.db.QueryRow(ctx, getUserEmailAndName, id)
	var i GetUserEmailAndNameRow
	err := row.Scan(&i.Name, &i.Email)
	return i, err
}

const getUserTicketsByID = `-- name: GetUserTicketsByID :many
SELECT
    t.id AS ticket_id,
    t.status AS ticket_status,
    t.passenger_name,
    t.passenger_relation,
    t.serial_no,
    t.ticket_code,
    t.booking_time,

    tr.id AS trip_id,
    tr.departure_time,
    tr.bus_type,
    t.price_paid as base_price,
    tr.direction,

    r.name AS route_name,

    (CASE
        WHEN tr.direction = 'INBOUND' THEN sp.address
        ELSE sd.address
    END)::text AS relevant_location,

    sp.address AS pickup_location,
    sd.address AS dropoff_location,

    (
        t.status = 'CONFIRMED' AND
        tr.status != 'CANCELLED' AND
        NOW() < (tr.departure_time - (tr.booking_close_offset_minutes * INTERVAL '1 minute'))
        )::BOOLEAN AS is_cancellable

FROM giki_transport.tickets t
JOIN giki_transport.trip tr ON t.trip_id = tr.id
JOIN giki_transport.routes r ON tr.route_id = r.id
JOIN giki_transport.stops sp ON t.pickup_stop_id = sp.id
JOIN giki_transport.stops sd ON t.dropoff_stop_id = sd.id
WHERE t.user_id = $1
AND tr.departure_time > (NOW() - INTERVAL '3 hours')
ORDER BY tr.departure_time DESC
`

type GetUserTicketsByIDRow struct {
	TicketID          uuid.UUID `json:"ticket_id"`
	TicketStatus      string    `json:"ticket_status"`
	PassengerName     string    `json:"passenger_name"`
	PassengerRelation string    `json:"passenger_relation"`
	SerialNo          int32     `json:"serial_no"`
	TicketCode        string    `json:"ticket_code"`
	BookingTime       time.Time `json:"booking_time"`
	TripID            uuid.UUID `json:"trip_id"`
	DepartureTime     time.Time `json:"departure_time"`
	BusType           string    `json:"bus_type"`
	BasePrice         int32     `json:"base_price"`
	Direction         string    `json:"direction"`
	RouteName         string    `json:"route_name"`
	RelevantLocation  string    `json:"relevant_location"`
	PickupLocation    string    `json:"pickup_location"`
	DropoffLocation   string    `json:"dropoff_location"`
	IsCancellable     bool      `json:"is_cancellable"`
}

func (q *Queries) GetUserTicketsByID(ctx context.Context, userID uuid.UUID) ([]GetUserTicketsByIDRow, error) {
	rows, err := q.db.Query(ctx, getUserTicketsByID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTicketsByIDRow
	for rows.Next() {
		var i GetUserTicketsByIDRow
		if err := rows.Scan(
			&i.TicketID,
			&i.TicketStatus,
			&i.PassengerName,
			&i.PassengerRelation,
			&i.SerialNo,
			&i.TicketCode,
			&i.BookingTime,
			&i.TripID,
			&i.DepartureTime,
			&i.BusType,
			&i.BasePrice,
			&i.Direction,
			&i.RouteName,
			&i.RelevantLocation,
			&i.PickupLocation,
			&i.DropoffLocation,
			&i.IsCancellable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWeeklyTicketCountByDirection = `-- name: GetWeeklyTicketCountByDirection :one
SELECT COUNT(*) FROM (
       -- Part 1: Confirmed Tickets (trips departing in the same week as reference_time)
       SELECT t.id
       FROM giki_transport.tickets t
                JOIN giki_transport.trip tr ON t.trip_id = tr.id
       WHERE t.user_id = $1
         AND t.status = 'CONFIRMED'
         AND tr.departure_time >= date_trunc('week', $2::timestamptz)
         AND tr.departure_time <  date_trunc('week', $2::timestamptz) + INTERVAL '7 days'
         AND tr.direction = $3

       UNION ALL

       -- Part 2: Active Holds (for trips departing in the same week as reference_time)
       SELECT h.id
       FROM giki_transport.trip_holds h
                JOIN giki_transport.trip tr ON h.trip_id = tr.id
       WHERE h.user_id = $1
         AND tr.direction = $3
         AND h.expires_at > NOW()
         AND tr.departure_time >= date_trunc('week', $2::timestamptz)
         AND tr.departure_time <  date_trunc('week', $2::timestamptz) + INTERVAL '7 days'
) as total_count
`

type GetWeeklyTicketCountByDirectionParams struct {
	UserID        uuid.UUID `json:"user_id"`
	ReferenceTime time.Time `json:"reference_time"`
	Direction     string    `json:"direction"`
}

// Counts CONFIRMED tickets + ACTIVE HOLDS for the same calendar week (Mon-Sun) as the given reference time, for a specific direction.
func (q *Queries) GetWeeklyTicketCountByDirection(ctx context.Context, arg GetWeeklyTicketCountByDirectionParams) (int64, error) {
	row := q.db.QueryRow(ctx, getWeeklyTicketCountByDirection, arg.UserID, arg.ReferenceTime, arg.Direction)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getWeeklyTicketStats = `-- name: GetWeeklyTicketStats :one
SELECT
    COUNT(CASE WHEN UPPER(tr.bus_type) = 'STUDENT' THEN 1 END) as student_count,
    COUNT(CASE WHEN UPPER(tr.bus_type) = 'EMPLOYEE' THEN 1 END) as employee_count,
    COUNT(*) as total_confirmed
FROM giki_transport.tickets t
JOIN giki_transport.trip tr ON t.trip_id = tr.id
WHERE
    tr.departure_time >= $1
    AND tr.departure_time < $2
    AND t.status = 'CONFIRMED'
`

type GetWeeklyTicketStatsParams struct {
	DepartureTime   time.Time `json:"departure_time"`
	DepartureTime_2 time.Time `json:"departure_time_2"`
}

type GetWeeklyTicketStatsRow struct {
	StudentCount   int64 `json:"student_count"`
	EmployeeCount  int64 `json:"employee_count"`
	TotalConfirmed int64 `json:"total_confirmed"`
}

func (q *Queries) GetWeeklyTicketStats(ctx context.Context, arg GetWeeklyTicketStatsParams) (GetWeeklyTicketStatsRow, error) {
	row := q.db.QueryRow(ctx, getWeeklyTicketStats, arg.DepartureTime, arg.DepartureTime_2)
	var i GetWeeklyTicketStatsRow
	err := row.Scan(&i.StudentCount, &i.EmployeeCount, &i.TotalConfirmed)
	return i, err
}

const incrementTripSeat = `-- name: IncrementTripSeat :exec


UPDATE giki_transport.trip
SET available_seats = available_seats + 1
WHERE id = $1 AND available_seats < total_capacity
`

// =============================================
// 5. CANCELLATION & REAPER (Cleanup)
// =============================================
func (q *Queries) IncrementTripSeat(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, incrementTripSeat, id)
	return err
}

const setTicketCancelled = `-- name: SetTicketCancelled :exec
UPDATE giki_transport.tickets
SET status = 'CANCELLED'
WHERE id = $1 AND status = 'CONFIRMED'
`

func (q *Queries) SetTicketCancelled(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setTicketCancelled, id)
	return err
}

const updateTrip = `-- name: UpdateTrip :exec
UPDATE giki_transport.trip
SET
    departure_time = $2,
    booking_open_offset_minutes = $3,
    booking_close_offset_minutes = $4,
    total_capacity = $5,
    -- Adjust available seats by the difference in capacity (if any), ensuring it doesn't go below 0
    available_seats = GREATEST(0, available_seats + ($5 - total_capacity)),
    base_price = $6,
    bus_type = $7,
    updated_at = NOW()
WHERE id = $1
`

type UpdateTripParams struct {
	ID                        uuid.UUID `json:"id"`
	DepartureTime             time.Time `json:"departure_time"`
	BookingOpenOffsetMinutes  int32     `json:"booking_open_offset_minutes"`
	BookingCloseOffsetMinutes int32     `json:"booking_close_offset_minutes"`
	TotalCapacity             int32     `json:"total_capacity"`
	BasePrice                 int32     `json:"base_price"`
	BusType                   string    `json:"bus_type"`
}

func (q *Queries) UpdateTrip(ctx context.Context, arg UpdateTripParams) error {
	_, err := q.db.Exec(ctx, updateTrip,
		arg.ID,
		arg.DepartureTime,
		arg.BookingOpenOffsetMinutes,
		arg.BookingCloseOffsetMinutes,
		arg.TotalCapacity,
		arg.BasePrice,
		arg.BusType,
	)
	return err
}

const updateTripManualStatus = `-- name: UpdateTripManualStatus :exec
UPDATE giki_transport.trip
SET manual_status = $2, updated_at = NOW()
WHERE id = $1
`

type UpdateTripManualStatusParams struct {
	ID           uuid.UUID   `json:"id"`
	ManualStatus pgtype.Text `json:"manual_status"`
}

func (q *Queries) UpdateTripManualStatus(ctx context.Context, arg UpdateTripManualStatusParams) error {
	_, err := q.db.Exec(ctx, updateTripManualStatus, arg.ID, arg.ManualStatus)
	return err
}
